### ISSUE TITLE
instantValidate doesn't apply to the 'required' validator

### ISSUE THREAD

**Issue by FintanK** [NewOldMax/react-material-ui-form-validator#10]
When using the 'instantValidate={ true }' option for the validation form it doesn't highlight required fields.

**Comment by NewOldMax** [comment]
@FintanK 
As you can see [here](https://github.com/NewOldMax/react-material-ui-form-validator/blob/master/src/ValidatorForm.jsx#L37) `required` rule works different than others. For my opinion it's a bad UX to show warning about `required` fields all the time. Anyway, you can override this behavior in any time by extending `ValidatorForm` component.
