### ISSUE TITLE
Step-by-step example does not work as expected

### ISSUE THREAD

**Issue by LonginusDi** [NewOldMax/react-material-ui-form-validator#101]
I was trying the step-by-step example from https://newoldmax.github.io/react-material-ui-form-validator/. I used the same code. However, when clicking on next, the form will go to step 2 while it didn't validate first step like in the example with a warning like this:

`react-dom.development.js:506 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.`

**Comment by NewOldMax** [comment]
Hi
what version do you use?

**Comment by ryankim07** [comment]
Hi, I'm using the latest version 2.0.8 and getting the same problem as above.  Also, your example is currently having the same issues.

**Comment by NewOldMax** [comment]
@ryankim07 I don't see such warning even on demo page

**Comment by ryankim07** [comment]
Ran on Firefox 66.0.3 and Chrome 73.0.3683.103 and both showing the same behavior.  Say, I go ahead and just click Next without touching the input field, it steps to the 2nd step showing required field.  I copied and pasted the code directly and it happens the same way.  Now, if I start inputing characters, then the validation kicks in for invalid email, which is right.  So I guess it's a issue when the input is blank and it's required.

**Comment by ryankim07** [comment]
Would you provide me any work around or other alternatives to validate the required fields?

**Comment by NewOldMax** [comment]
@ryankim07 So I refactored that example a bit, you can test is as well

**Comment by ryankim07** [comment]
Thanks for taking refactoring!!!
