### ISSUE TITLE
Update OnBlur Wiki page

### ISSUE THREAD

**Issue by kmordan24** [NewOldMax/react-material-ui-form-validator#103]
Suggest updating the OnBlur wiki example to no longer use this.refs and string refs as they have been deprecated since React 16.3.

This is an example of a way to do it using React.createRef():

    constructor(props) {
        super(props);
        this.emailRef = React.createRef();
        this.state = { email:'' };
        this.handleBlur = this.handleBlur.bind(this);
        this.handleChange = this.handleChange.bind(this);
        ...
    }
    handleBlur = (event) => {
        if (event.target.name === 'email') {
            this.emailRef.current.validate(event.target.value, true);
        }
    };
    handleChange = (event) => {
        const { ...rest } = this.state;
        rest[event.target.name] = event.target.value;
        this.setState(rest);
    };
    render() {
        const  { email } = this.state;
        ...
        <TextValidator
                            label="Email Address"
                            onChange={this.handleChange}
                            onBlur={this.handleBlur}
                            name="email"
                            type="email"
                            ref={this.emailRef}
                            validators={['required', 'isEmail']}
                            errorMessages={['this field is required', 'Not a valid email address']}
                            value={email}
                            required
                            fullWidth
                            autoComplete="email"
                            autoFocus
                            margin="normal"
                        />
        }

**Comment by NewOldMax** [comment]
It's fixed now, thanks
