### ISSUE TITLE
Can't find 'label' prop in ValidatorComponentProps

### ISSUE THREAD

**Issue by PSEH-3** [NewOldMax/react-material-ui-form-validator#104]
I am using "@types/react-material-ui-form-validator": "^2.0.0" for react-material-ui-form-validator. It would be nice if we can add 'label' props in ValidatorComponentProps.

Or, please let me know if there is a way to pass 'label' prop in typescript.

**Comment by NewOldMax** [comment]
Hi,

`@types` package is maintained [here](https://github.com/DefinitelyTyped/DefinitelyTyped) so you can create issue there
