### ISSUE TITLE
isEmail validation fails 

### ISSUE THREAD

**Issue by aidenvyas** [NewOldMax/react-material-ui-form-validator#106]
isEmail validation fails for example "email@f.c" 

**Image:**
![isEmail](https://user-images.githubusercontent.com/8621923/55934259-a317e480-5c4d-11e9-9f01-7e8f1be5c16a.PNG)

` <TextValidator             
              label="Correo Electrónico"
              onChange={event => this.onInputChange(event.target)}
              name="email"
              variant="outlined"
              value={this.state.email}
              validators={["required", "isEmail"]}
              errorMessages={[
                "Correo Electrónico is required",
                "email no es válido"
              ]}
            />`
 i've been the above mentioned code and can go through the image for further info

**Comment by NewOldMax** [comment]
Hi
I don't see any errors on your image.

**Comment by aidenvyas** [comment]
@NewOldMax  It should throw an error for the email syntax but it is not

**Comment by NewOldMax** [comment]
If you want to have full check for all possible emails (like, `.c` is not a valid domain name right now) you must implement your own validation. Also there can be case when we have some organization with internal domain names and they can have some custom format, like `email@company.w` or whatever.

So default `isEmail` rule can handle only general case, if you need more strict rule, you must do it by yourself
