### ISSUE TITLE
supports @material-ui 4.0.0

### ISSUE THREAD

**Issue by minhna** [NewOldMax/react-material-ui-form-validator#107]
Hi, @material-ui version 4 is released.
Please make a new version to support it.
Thank you very much.

**Comment by NewOldMax** [comment]
You can use current version with 4 as well, just ignore installation warning.
I will update dependencies later

**Comment by minhna** [comment]
Thank you.

**Comment by NewOldMax** [comment]
@minhna Check the 2.0.9 version

**Comment by minhna** [comment]
@NewOldMax Thank you very much.
