### ISSUE TITLE
Dependant Controls

### ISSUE THREAD

**Issue by cam-nutrien** [NewOldMax/react-material-ui-form-validator#109]
I have 2 controls that depend on each other: one is a start and the other is an end. End must be larger than a Start. I put my custom validation on the End and all works fine, unless the user edits the Start to make it less than the End (which was previously smaller than the Start). The validation on End continues to show it as invalid. Is it possible to validate more than one control at a time or have the validation of control 1 cause a re-validation of control 2?

Thanks

**Comment by NewOldMax** [comment]
Hi, you can run validation manually for specific input or whole form via ref
```
this.formRef.isFormValid(false);
this.inputRef.validate(value);
```
