### ISSUE TITLE
Updating a list of errors

### ISSUE THREAD

**Issue by rowrowrowrow** [NewOldMax/react-material-ui-form-validator#110]
Hi,

I'd like to show the user a list of the errors in the form that updates as the user corrects those errors. Steps:

1. Submit form
2. Show errors
3. Update list of errors as corrected

1 is solved by the onSubmit but I'm questionable about my approach to 2 & 3. What do you recommend?

**Comment by NewOldMax** [comment]
Hi,
can you clarify with image/screenshot/gif-animation what do you want to achieve?

**Comment by rowrowrowrow** [comment]
Yep. I can't provide an image but I can mock the result with fake fields. 

So after they submit the form I will display a list of the errors for the user to correct like the following: 

1. Password is invalid (acceptable characters = 923r0fq90813yr0)
2. Email is not valid
3. Please select an image
4. Specify your age

Then, let's say the user corrects the Password field. The list should automatically update to the following WITHOUT the user needing to submit the form so the user doesn't think errors exist that really don't exist:

1. Email is not valid
2. Please select an image
3. Specify your age

Thanks!!!

**Comment by NewOldMax** [comment]
So first solution: display all matched validations for each input - https://codesandbox.io/s/4xiun
Second one: display all matched validations in one place - https://codesandbox.io/s/asyncvalidationtest-xri9f

**Comment by rowrowrowrow** [comment]
Thanks the second one resolved my issue in a way that was flexible enough to work with everything else I had to do. Thanks!!!!
