### ISSUE TITLE
TypeScript Validator Component

### ISSUE THREAD

**Issue by jaydedm** [NewOldMax/react-material-ui-form-validator#111]
Hello! I know this is a JS library, but I've been able to get full, normal functionality just fine with TypeScript EXCEPT when I'm trying to add the custom Validator for a checkbox as shown for the docs. 

```
<CheckboxValidatorElement
              validators={['isShippingAddressPOBox']}
              errorMessages={['You cannot have a PO Box set as a default Shipping Address']}
              value={address.isShipping}
/>
```
Originally this was throwing an error:
JSX element class does not support attributes because it does not have a 'props' property. 

Then I went into the `CheckboxValidatorElement` and added an actual props property, and got a whole other slew of errors. Did something like this: 

```
  props : {
    errorMessages: string[],
    validators: string[],
    value: boolean
  }
```

My component looks like this. Originally had `this` in place of the `super`, but was getting a TS error. When adding //@ts-ignore above all the uses of `this`, I was still getting the same props property error as described above.

```
import React from 'react';
import Checkbox from '@material-ui/core/Checkbox';
import { ValidatorComponent } from 'react-material-ui-form-validator';
import {useStyles} from "./addressBook.styles";

const classes = useStyles()

class CheckboxValidatorElement extends ValidatorComponent {


  render() {
    const { errorMessages, validators, requiredError, value, ...rest } = super.props;

    return (
      <div>
        <Checkbox
          {...rest}
          ref={(r) => { super.input = r; }}
        />
        {super.errorText()}
      </div>
    );
  }

  errorText() {
    const { isValid } = super.state;

    if (isValid) {
      return null;
    }

    return (
      <div>
        {super.getErrorMessage()}
      </div>
    );
  }
}

export default CheckboxValidatorElement;
```

Any ideas on how I can get checkbox validation with TypeScript using your library?

**Comment by mlake** [comment]
I'm in the same boat

**Comment by NewOldMax** [comment]
@jaydedm hi

unfortunately I don't use TypeScript so I can't help you with it

**Comment by HaoDaWang** [comment]
@jaydedm  Hi~, try this one？
```shell
yarn add @types/react-material-ui-form-validator -D
```

**Comment by NewOldMax** [comment]
Closed as inactive
