### ISSUE TITLE
Confirm password validate

### ISSUE THREAD

**Issue by adhenrique** [NewOldMax/react-material-ui-form-validator#113]
Is it possible to perform one validation dependent on another? That is, field 2 is only valid if its value is equal to field 1 ...
Usually this rule is used in password fields and confirm your password.

**Comment by NewOldMax** [comment]
You can see example in [usage](https://github.com/NewOldMax/react-material-ui-form-validator#usage) section, also check this [issue](https://github.com/NewOldMax/react-form-validator-core/issues/54) as well
