### ISSUE TITLE
Handle error spacing/sizing

### ISSUE THREAD

**Issue by darrensw777** [NewOldMax/react-material-ui-form-validator#12]
Is there a way to load the errors into a container already set under each form field?

The problem I have is that the whole form moves (each field below the first moves down) to accommodate the errors and from a UI/UX point of view it's kind of messy.

Not strictly a plug-in issue, just wanted to ask - am going to look into the code myself and see how I get on. Pretty new to React.

**Comment by NewOldMax** [comment]
Hi,
Can you provide some screens of expected result?

**Comment by darrensw777** [comment]
Hi, sure, please see screenshot
![material-ui-validation](https://cloud.githubusercontent.com/assets/16285693/26541550/00ed1810-444e-11e7-9e07-c89fd80e213a.jpg)

**Comment by NewOldMax** [comment]
You can try to override validator components
````javascript
import React from 'react';
import TextField from 'material-ui/TextField';
import { ValidatorComponent } from 'react-material-ui-form-validator';

export default class TextValidator extends ValidatorComponent {

    render() {
        const { errorMessages, validators, requiredError, errorText, ...rest } = this.props;
        const { isValid } = this.state;
        const errorMessage = (!isValid && this.getErrorMessage()) || errorText; // <---- do something with error message
        return (
            <TextField
                {...rest}
                ref={(r) => { this.input = r; }}
            />
        );
    }
}
````

For me, to solve this spaces issues, I just use custom styling for error messages
````javascript
const errorStyle = {
        position: 'absolute',
        marginBottom: '-22px',
        color: red300,
};
````

**Comment by darrensw777** [comment]
Yeah great idea, many thanks - still getting my head around React - it's really flexible which is great but with so many ways to do things it can also get confusing pretty fast!

I also have another question about custom errors like isPasswordMatch, should I add as another issue?

**Comment by NewOldMax** [comment]
Create a new one, current issue is done
