### ISSUE TITLE
validate inputs and show errors on load?

### ISSUE THREAD

**Issue by KWasko** [NewOldMax/react-material-ui-form-validator#121]
Hello Does anybody know how to validate inputs and show error messages on component load?

In onChange event everything works fine, but I need to validate inputs as soon as it receive value from backend side.

Regards

**Comment by NewOldMax** [comment]
Please create some example on https://codesandbox.io/s/ so it will be better to analyze

**Comment by FroggDev** [comment]
if you are using react-form-validator you can try:

`{your form ref}.current.isFormValid(false);`

from https://www.npmjs.com/package/react-form-validator-core

> dryRun = false to show validation errors on form

**Comment by agjs** [comment]
@NewOldMax There is no need to produce an example for this. Currently, validation is only trigger when you are actually typing in stuff to <TextValidator />. If you pre-fill your input fields by the data coming from the props or whatever, validation is not triggered. It seams that validation only reacts to onChange event and nothing else.

**Comment by KWasko** [comment]
thanks for your responses, the answer was as simple as create hook and run isFormValid(false) inside it;

useEffect(() => {
    if (formRef.current != null) {
      formRef.current.isFormValid(false);
    }
  }, [formRef.current]);

**Comment by agjs** [comment]
Awesome. Will take a look in the morning. Thanks :-)
