### ISSUE TITLE
custom validation doesn't support hooks 

### ISSUE THREAD

**Issue by PRASHANTPR7** [NewOldMax/react-material-ui-form-validator#127]
https://codesandbox.io/embed/dreamy-paper-yf21h?fontsize=14&hidenavigation=1&theme=dark

i am trying to add two custom validations with useEfect() but it doesn't work .

please check above sandbox

**Comment by NewOldMax** [comment]
@PRASHANTPR7
Hi,
your custom validation rule must return `true` or `false` value in order to use it

**Comment by tomasalles** [comment]
Same issue here, were u able to fix it prash?

**Comment by NewOldMax** [comment]
it works with hooks

**Comment by tomasalles** [comment]
As soon as I type it gets me validation false, can't understand why...

validation function : 
```
useEffect(() => {
    ValidatorForm.addValidationRule("isColorNameUnique", value => {
      colors.every(({ name }) => name.toLowerCase() !== value.toLowerCase());
    });
    ValidatorForm.addValidationRule("isColorUnique", value => {
      colors.every(
        ({ color }) =>
          color.toLowerCase() !== formState.currentColor.toLowerCase()
      );
    });
  });
```

my state array:
```
const [colors, setColors] = useState([
    { color: "#c4482c", name: "#c4482c" },
    { color: "#e4567f", name: "#e4567f" }
  ]);
```

validator component:
```
<ValidatorForm onSubmit={addNewColor}>
          <TextValidator
            value={formState.currentColorName}
            name="currentColorName"
            onChange={handleChange}
            validators={["required", "isColorNameUnique", "isColorUnique"]}
            errorMessages={[
              "this field is required",
              "color name must be unique",
              "color must be unique"
            ]}
          />
          <Button
            variant="contained"
            type="submit"
            color="primary"
            style={{ backgroundColor: formState.currentColor }}
          >
            Add Color
          </Button>
        </ValidatorForm>
```
any help?

**Comment by NewOldMax** [comment]
validation function must return a value (true or false) or a promise which will return true or false

**Comment by NewOldMax** [comment]
note that `every` function will return `true` for case of empty array

**Comment by tomasalles** [comment]
facepalm...

sry mate... forgot to return... tyvm btw

**Comment by kabulzhan** [comment]
How to implement custom validation with componentDidMount equivalent of Hooks?
In the examples above, useEffect() is running every time, which is more like componentDidUpdate. The validation rule is getting redefined every time.
But, if you use an empty array in useEffect ( ()=> {...AddValidationRule... } , [ ]), the validation rule does not work correctly. It does not check the updated versions of "colors" hook.
