### ISSUE TITLE
Trying to validate onBlur

### ISSUE THREAD

**Issue by aks7665** [NewOldMax/react-material-ui-form-validator#128]
I am getting this error : -
TypeError: Cannot read property 'validate' of undefined
handleBlur
src/views/Login/Login.js:81
  78 | };
  79 | 
  80 | const handleBlur = (event) => {
> 81 |   ref[event.target.name].validate(event.target.value);
     | ^  82 | }
  83 | 
  84 | return (

export default function Login(props) {
  const classes = useStyles();

  const [state, setState] = useState({
    formData: {
      email: "",
      password: ""
    },
    submitted: false
  });

  const { formData, submitted } = state;

  const ref = React.useRef(null);

  const handleChange = event => {
    const { formData } = state;
    formData[event.target.name] = event.target.value;
    setState({ formData });
  };

  const handleSubmit = () => {
    const prevState = state;
    prevState.submitted = false;
    setState(prevState);
    console.log(state)
  };

  const handleBlur = (event) => {
    ref[event.target.name].validate(event.target.value);
  }

export default function Login(props) {
  const classes = useStyles();

  const [state, setState] = useState({
    formData: {
      email: "",
      password: ""
    },
    submitted: false
  });

  const { formData, submitted } = state;

  const ref = React.useRef(null);

  const handleChange = event => {
    const { formData } = state;
    formData[event.target.name] = event.target.value;
    setState({ formData });
  };

  const handleSubmit = () => {
    const prevState = state;
    prevState.submitted = false;
    setState(prevState);
    console.log(state)
  };

  const handleBlur = (event) => {
    ref[event.target.name].validate(event.target.value);
  }
}

**Comment by NewOldMax** [comment]
@aks7665 there may be some problem with your code
also [onBlur](https://newoldmax.github.io/react-material-ui-form-validator/) example works well
