### ISSUE TITLE
prop-types should be a dependency

### ISSUE THREAD

**Issue by oliviertassinari** [NewOldMax/react-material-ui-form-validator#129]
I have noticed the following warning:
`warning "react-material-ui-form-validator > react-form-validator-core@0.6.4" has unmet peer dependency "prop-types@^15.0.0".`

I would encourage to set prop-types as a dependency (not a peer), I believe it's the encouraged approach by the react team.

**Comment by NewOldMax** [comment]
@oliviertassinari Hi
thanks for reporting
fixed in 2.0.10

**Comment by oliviertassinari** [comment]
Thanks!
