### ISSUE TITLE
isPasswordMatch

### ISSUE THREAD

**Issue by darrensw777** [NewOldMax/react-material-ui-form-validator#13]
When adding the 'isPasswordMatch' functionality, it works as expected but starts checking as soon as anything is entered into any form field, therefore displaying the error before the user has even got to the field.

Is there any way to delay the initial check until the form is submitted, then after that, onChange?

**Comment by NewOldMax** [comment]
Try to set `instantValidate` as `true` for `ValidatorForm`

**Comment by NewOldMax** [comment]
Also you can check [advanced usage](https://github.com/NewOldMax/react-material-ui-form-validator/wiki/How-to-onBlur), you can see how to trigger validation manually.

**Comment by darrensw777** [comment]
Many thanks, will try this evening. Appreciated.

**Comment by kalanka29** [comment]
if the validation of `isEmail` is for `email` type input filed   not pass,but the values will be passed through the  Submit button.Is there a way to block the transfer of data on submit without passing the form validations.

**Comment by NewOldMax** [comment]
Hi, @kalanka29 
Can you create a new issue for your question? And provide more details, maybe code example

**Comment by darrensw777** [comment]
Many thanks @NewOldMax, works perfectly. Apologies for the late reply.
