### ISSUE TITLE
how can I validate for minLength 

### ISSUE THREAD

**Issue by jagannath-swarnkar** [NewOldMax/react-material-ui-form-validator#131]
I want to validate my password for {minLength:8, isContainAlpha, isContainNumber}

**Comment by Beamanator** [comment]
You could probably use `matchRegexp:^[0-9a-zA-Z]{8,}$`

**Comment by NewOldMax** [comment]
@jagannath-swarnkar 
for minLenght there is built-in rule `minStringLength`
for isContainAlpha you can use `matchRegexp:^[a-zA-Z]$` for example
and for isContainNumber you can use `matchRegexp:^[0-9]$`
play around with those
