### ISSUE TITLE
How to give validation for date picker

### ISSUE THREAD

**Issue by vnanaware** [NewOldMax/react-material-ui-form-validator#132]
Below is my date picker how to add  'react-material-ui-form-validator' in this.

<MuiPickersUtilsProvider utils={DateFnsUtils}> 
                  <Grid container justify="space-around">

                    <KeyboardDatePicker
                      {...rest}
                      margin="normal"
                      label={props.strTitle}
                      format="dd/MM/yyyy"
                      value={props.strDate}
                      onChange={handleDateChange}
                      KeyboardButtonProps={{
                        'aria-label': 'change date',
                      }}
                    /> 
                    
                  </Grid>
                </MuiPickersUtilsProvider>

**Comment by NewOldMax** [comment]
you can see some example how to add validation to custom inputs [here](https://github.com/NewOldMax/react-material-ui-form-validator/wiki/Material-ui-v1-datepickers-example)
