### ISSUE TITLE
Validate pre-filled values

### ISSUE THREAD

**Issue by mbelic** [NewOldMax/react-material-ui-form-validator#134]
Hello,
I have set up validation of the form and everything is working nicely. 

However I now have an issue where state of the component can start with pre-filled values and on submit of the form the validators fire up and report that the field must be filled before the submission. I am not touching the pre-filled fields in any way.

Is there any way to force check of the field even though there was no interaction on it and it **is** valid?

Thank you.

**Comment by NewOldMax** [comment]
@mbelic hi
please reproduce your issue here: https://codesandbox.io/s/new

**Comment by mbelic** [comment]
Hey, 

After recreating the example on codesandbox and re-checking code I found an data type error inside my validator which caused the issue.
Everything is working as it should now, thank you.

Thank you for reply and your work!
