### ISSUE TITLE
Legacy Context API

### ISSUE THREAD

**Issue by ConradoZA** [NewOldMax/react-material-ui-form-validator#136]
Thanks for your work, this library it's really useful.
But right now I'm receiving this warning, using React 16.13.1

> Warning: Legacy context API has been detected within a strict-mode tree.
> 
> The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.
> 
> Please update the following components: TextValidator, ValidatorForm
> 
> Learn more about this warning here: https://fb.me/react-legacy-context

I hope you can update your components so  it's still this useful in the future!

**Comment by wsoaresfilho** [comment]
I am having the same issue. I hope you can get this fixed so this great package can still work in the future.

**Comment by NewOldMax** [comment]
Yes I know about that, but didn't find proper solution to use new context API without losing backward compatibility. So if you have a nice solution we can discuss it

**Comment by ConradoZA** [comment]
I'm afraid I don't have any nice solution...

**Comment by ConradoZA** [comment]
I'm closing the issue as you are already aware of the problem.

Thanks for the answer!
