### ISSUE TITLE
Better examples

### ISSUE THREAD

**Issue by cmocanu** [NewOldMax/react-material-ui-form-validator#137]
Hey!

Thanks for the library, it's exactly what I needed and very easy to add when using material-ui.

Still, it took me a while to figure out how to use it my case, because I wanted to use it inside a modal, and I didn't realize it's possible to submit a form with a button [outside](https://stackoverflow.com/questions/7020659/submit-form-using-a-button-outside-the-form-tag) the form. It would be nice to have this in the demo.

**Comment by NewOldMax** [comment]
@cmocanu Hi
you can check this example: https://codesandbox.io/s/fast-feather-wojig
