### ISSUE TITLE
Pass 'event' in submit(event) ->  this.props.onSubmit();

### ISSUE THREAD

**Issue by laura-rodriguez** [NewOldMax/react-material-ui-form-validator#14]
I have a form where I can receive feedback from the server so I would need to call event.preventDefault() after ValidationForm submit.
By now, it is not possible to "catch" the event after all form validations have passed.

**Comment by NewOldMax** [comment]
Hi,
You can see that `event.preventDefault()` is [already called](https://github.com/NewOldMax/react-material-ui-form-validator/blob/master/src/ValidatorForm.jsx#L63)

**Comment by laura-rodriguez** [comment]
Hi!

Yes, but then you have this:  if (result) {this.props.onSubmit();} so the event is not passed to the props.onSubmit.

**Comment by NewOldMax** [comment]
Yes, it's not passed. But if you only need to do `preventDefault`, you don't need to catch event.

**Comment by laura-rodriguez** [comment]
My scenario is next (maybe I am using a wrong approach). I have a basic login form with user and password fields. User and password are two TextValidator inside a validation form, with 'required' validation. Once the user enters both inputs and press submit the server can return an error which should be displayed in the form. By now, as that logic is custom and it's passed to validatorForm as "customHandleSubmit" in onSubmit prop,  I am not able to call prevent default from my customHandleSubmit, so the form is rendered again without showing the error.

**Comment by laura-rodriguez** [comment]
Sorry, I just realized that I was having issues with the routing and with the form. Thanks for your support.
