### ISSUE TITLE
TypeError: Cannot read property 'detachFromForm' of undefined

### ISSUE THREAD

**Issue by JerryFireman** [NewOldMax/react-material-ui-form-validator#140]
Hi, I am using TextValidator successfully but whenever I try to use SelectValidator, even in the simplest cases, I receive the above error message. Am I doing something wrong?

**Comment by sannrs** [comment]
Hey @JerryFireman i ended up running into the same problem and figuring it out seems like it needs to be wrapped in a Validator Form

```
import { ValidatorForm } from 'react-material-ui-form-validator';

<ValidatorForm> 
 <ComponentYouAreTesting>
</ValidatorForm> 
```

**Comment by JerryFireman** [comment]
Hi, that worked for me too. Thanks very much for your help!

**Comment by JerryFireman** [comment]
Problem fixed. Thank you David!

**Comment by sannrs** [comment]
No worries i thought that this only affected 'attachToForm' but seems to have fixed 'detachFromForm' as well
I have readded my answer incase anyone else runs into to problem with either of them

```
 import { ValidatorForm } from 'react-material-ui-form-validator';

 <ValidatorForm>
     <ComponentYouAreTesting>
 </ValidatorForm>
```

**Comment by behnam-basketasia** [comment]
@JerryFireman I cant find out  how do you fixed it? i faced with same issue.

**Comment by JerryFireman** [comment]
@behnam-basketasia here's how i fixed it ..

              <ValidatorForm className={classes.form} onSubmit={props.approveToken}>
                <FormControl className={classes.formControl}>
                  <SelectValidator
                    name='tokenToApprove'
                    value={props.tokenToApprove}
                    onChange={props.handleChange}
                    label="Token"
                    validators={['required']}
                    errorMessages={['This field is required']}
                  >
                    <MenuItem><em>None</em></MenuItem>
                    <MenuItem value={"WETH"}>WETH</MenuItem>
                    <MenuItem value={"DAI"}>DAI</MenuItem>
                    <MenuItem value={"MKR"}>MKR</MenuItem>
                  </SelectValidator>
                </FormControl>
                <br/>
                <FormControl className={classes.formControl}>
                  <TextValidator
                      label="Amount"
                      onChange={props.handleChange}
                      name="approvalAmount"
                      value={props.approvalAmount}
                      validators={['minFloat:0.0000001']}
                      errorMessages={['Positive value must be entered']}
                  />
                </FormControl>
                <StyledButton onClick={props.approveToken} type="submit">
                    Approve
                </StyledButton>
              </ValidatorForm>
