### ISSUE TITLE
Incompatible when using MUI's Input and InputLabel instead of TextField? 

### ISSUE THREAD

**Issue by jameschetwood** [NewOldMax/react-material-ui-form-validator#143]
I'm not using the TextField from Material UI directly. Instead Im using the the lower level components of Input, InputLabel, etc as I needed to customise the input. 

You can see an example in the docs: 
https://material-ui.com/components/text-fields/#input-adornments

Does that mean that I can't use this library? The docs show how to use it as a replacement for TextField but don't cover other usages.

**Comment by NewOldMax** [comment]
@jameschetwood hi
if you want to use custom validation component you should implement it by yourself
you can see example here https://github.com/NewOldMax/react-material-ui-form-validator/blob/master/src/TextValidator.jsx
