### ISSUE TITLE
Problem with CheckboxValidatorElement with latest release

### ISSUE THREAD

**Issue by LeJav** [NewOldMax/react-material-ui-form-validator#146]
Hello,
I have created a CheckboxValidatorElement according to your example. It worked nice since more than one year. Great!
I have now updated to the latest releases last week, and also did "npm audit fix", and now CheckboxValidatorElement does not work anymore.
Form does not load, and I have this error in console: Uncaught TypeError: _this.form is undefined
In Chrome, the error is: Uncaught TypeError: Cannot read property 'attachToForm' of undefined
    at CheckboxValidatorElement.ValidatorComponent._this.configure 

What is wrong now?
How can I solve this problem?
Many thanks for your work and your help.

**Comment by NewOldMax** [comment]
@LeJav hi
there was a major update of related iibrary - react-form-validator-core
so this package was updated to work with it, but your custom components should be updated manually
you must change `render` method of your custom components to `renderValidatorComponent`

**Comment by LeJav** [comment]
Many thanks for your quick reply. That solved my problem!
