### ISSUE TITLE
Custom validation rule triggers api call multiple times

### ISSUE THREAD

**Issue by rahuljadhav-sumasoft** [NewOldMax/react-material-ui-form-validator#154]
Hi,

I am using this library for form validations, I have added one custom validation to check name uniqueness. it calls API to check name uniqueness.   I am using ["applyUniqueNameValidation", "required", "minStringLength:10", "maxStringLength:10"] validators, but I have noticed that when I submit form it calls name uniqueness API multiple time(5 to be exact). This is causing a performance issue. not sure what I am doing wrong.

**Comment by NewOldMax** [comment]
@rahuljadhav-sumasoft hi
please create minimal example here: https://codesandbox.io/s/

**Comment by rahuljadhav-sumasoft** [comment]
Thanks for the reply.

Please find https://codesandbox.io/s/sharp-bose-tmx33?file=/src/App.js link. If you check the console log you will see applyUniqueTSNValidation logged 5 times. I have not provided the actual API call but if the rule is getting called 5 times means api call will get called 5 times on submit.

Thanks

**Comment by NewOldMax** [comment]
@rahuljadhav-sumasoft please check 2.1.3 version
issue should be fixed

**Comment by rahuljadhav-sumasoft** [comment]
@NewOldMax I don't see version 2.1.3 is rolled out yet. How can I check with version 2.1.3?

Thanks.

**Comment by NewOldMax** [comment]
@rahuljadhav-sumasoft it's already available for installation, npm just not showing it yet

**Comment by rahuljadhav-sumasoft** [comment]
Thanks.

Will check and get back to you.

**Comment by rahuljadhav-sumasoft** [comment]
@NewOldMax New version works. Thanks a lot.
