### ISSUE TITLE
Submit button error "Unhandled Promise Rejection: ReferenceError: regeneratorRuntime is not defined"

### ISSUE THREAD

**Issue by peacechen** [NewOldMax/react-material-ui-form-validator#155]
react-material-ui-form-validator 2.1.3 throws an exception when its `onSubmit` callback is fired.

>index.js:236 Possible Unhandled Promise Rejection: ReferenceError: regeneratorRuntime is not defined
    at ValidatorForm.js:137
    at ValidatorForm._this.validate (ValidatorForm.js:168)
    at ValidatorForm.js:125

`regeneratorRuntime` isn't in this repo directly, but it's used by `react-form-validator-core`.  The bump of `react-form-validator-core` from 1.0.1 to 1.1.0 causes this problem.

Reverting react-material-ui-form-validator to 2.1.2 prevents this exception.

**Comment by NewOldMax** [comment]
@peacechen please check 2.1.4 version

**Comment by peacechen** [comment]
2.1.4 works great. Thanks for the quick fix 👍
