### ISSUE TITLE
Make event accessible onError

### ISSUE THREAD

**Issue by RussellSanders1** [NewOldMax/react-material-ui-form-validator#157]
I would like to stopPropagation of the submission event onError, but it seems FormValidator only has access to the errors themselves when onError is called.  If there is another way to accomplish this goal, point me in the right direction, but I think the simplest thing from a usability standpoint would be to expose the event like onSubmit does.

**Comment by NewOldMax** [comment]
@RussellSanders1 Hi,
if you really want to do something more with submit event, you can try override it
```jsx
class CustomForm extends ValidatorForm {
    submit = (event) => {
         if (event) {
             event.preventDefault();
             event.persist();
             event.stopPropagation();
         }
         super.submit(); //call original submit method
    }
}
```
if you want to do stopPropagation only when error detected, then you can just override submit method deeper
```jsx
class CustomForm extends ValidatorForm {

    submit = (event) => {
        if (event) {
            event.preventDefault();
            event.persist();
        }
        this.errors = [];
        this.walk(this.childs).then((result) => {
            if (this.errors.length) {
                event.stopPropagation();
                this.props.onError(this.errors);
            }
            if (result) {
                this.props.onSubmit(event);
            }
            return result;
        });
    }
}
```
After all you must use your CustomFrom instead of ValidatorForm

**Comment by RussellSanders1** [comment]
thanks for pointing out extending is a thing, I forgot
