### ISSUE TITLE
React 17 Compatibility

### ISSUE THREAD

**Issue by willashe** [NewOldMax/react-material-ui-form-validator#158]
Hi, I see that you have releases for both `react-material-ui-form-validator` and `react-form-validator-core` that specifically mention React 17 support, but when I try to install `react-material-ui-form-validator` with React 17 it is failing peer dependencies:

```npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.0 || ^16.0.0" from create-react-context@0.3.0
npm ERR! node_modules/react-form-validator-core/node_modules/create-react-context
npm ERR!   create-react-context@"^0.3.0" from react-form-validator-core@1.1.1
npm ERR!   node_modules/react-form-validator-core
npm ERR!     react-form-validator-core@"1.1.1" from react-material-ui-form-validator@2.1.4
npm ERR!     node_modules/react-material-ui-form-validator
npm ERR!       react-material-ui-form-validator@"2.1.4" from the root project
```

`react-form-validator-core` apparently still requires `create-react-context@^0.3.0` which is only compatible with React up to v16.  Is there any way to get `react-material-ui-form-validator` working with React 17?  Seems like `create-react-context@^0.3.0` should no longer be a dependency of `react-form-validator-core` if it uses native context.

Thank you

**Comment by NewOldMax** [comment]
@willashe hi
`create-react-context` package is used for backward compatibility with old react versions. Personally I have a project with react 15.x and it cannot be updated, so this package allows to use validation forms for old projects

if you're using npm v7 then you can use `--legacy-peer-deps` flag to avoid such installation problem
