### ISSUE TITLE
No ref forwarding on textValidator

### ISSUE THREAD

**Issue by TristanElain** [NewOldMax/react-material-ui-form-validator#159]
**Context**
Using `TextValidator` component I was hoping to manipulate the input field in my form with `useRef`.

**Issue**
Ref is not forwarded towards the input, it controls the `TextValidator` component directly.

Is it possible to forward the ref to `TextField` ?

**Comment by zachrickards** [comment]
@TristanElain Pass the ref as inputRef={ref} rather than ref={ref}

**Comment by TristanElain** [comment]
You're right ! Thank you for that 👍
