### ISSUE TITLE
Child components within ValidatorForm wrapped by plain divs

### ISSUE THREAD

**Issue by alishahwee** [NewOldMax/react-material-ui-form-validator#163]
## Expected Behavior

![Screen Shot 2021-07-27 at 10 49 02 AM](https://user-images.githubusercontent.com/59731668/127185692-2d95fc65-f921-46e6-ae2b-12550a4c7e5a.png)
![Screen Shot 2021-07-27 at 10 49 22 AM](https://user-images.githubusercontent.com/59731668/127185698-bd46a249-8018-43e1-832a-92ec55dd0990.png)

## Current Behavior

![Screen Shot 2021-07-27 at 10 39 43 AM](https://user-images.githubusercontent.com/59731668/127184450-09c4c926-360a-4e06-823a-4b54cbeb9c86.png)
![Screen Shot 2021-07-27 at 10 40 18 AM](https://user-images.githubusercontent.com/59731668/127184471-b64d72f3-8fb7-4db5-9666-25703316d4c1.png)

## Steps to Reproduce

1. Update react-material-form-validator from 2.0.10 to 2.1.4

## Detailed Description

I was trying to update our dependencies, and when this package got updated, it wrapped all the select and text validator components with a plain div (present everywhere in the website). It causes our CSS to not come through anymore which messes up the formatting (e.g. 100% width does not apply anymore).

Code was written to match directions provided. No custom validator components were used (just some custom rules).

**Comment by NewOldMax** [comment]
Internal dependency had breaking change in order to support new Context API so markup was changed
you can use `containerProps` prop to pass required styles/classes to div component
