### ISSUE TITLE
Material UI 5 support

### ISSUE THREAD

**Issue by timgerhard** [NewOldMax/react-material-ui-form-validator#165]
Hi, I was wondering if a release with support for material-ui 5 is planned anytime soon? I think it shouldn't be too hard since there weren't any breaking changes for the `<TextField>` and `<Select>` Components.

As far as I can see, you would only need to change the imports from:
```
/* eslint-disable */
import React from 'react';
import TextField from '@material-ui/core/TextField';
/* eslint-enable */
import { ValidatorComponent } from 'react-form-validator-core';
```

to:
```
/* eslint-disable */
import React from 'react';
import TextField from '@mui/material/TextField';
/* eslint-enable */
import { ValidatorComponent } from 'react-form-validator-core';
```

and update the @types package (for typescript support).

**Comment by NewOldMax** [comment]
@timgerhard Hi
mui v5 is release candidate still so I won't update package until it will be production ready

**Comment by NewOldMax** [comment]
also @types package is not handled by me so you will need to ask about it in corresponding repository

**Comment by adeel-ali-atp** [comment]
It's out. 

https://twitter.com/MaterialUI/status/1438518915236126723

**Comment by timgerhard** [comment]
@NewOldMax how long until we can expect a new version? :)

**Comment by NewOldMax** [comment]
next week I guess

**Comment by alexdaube** [comment]
#166

**Comment by NewOldMax** [comment]
v3.0.0 is out
