### ISSUE TITLE
matchRegExp Documentation

### ISSUE THREAD

**Issue by kevincianfarini** [NewOldMax/react-material-ui-form-validator#17]
I'm going to need to use matchRegExp validation in order to validate some phone numbers. The documentation has nothing on how to use matchRegExp. Do you think you could update the docs and explain this?

**Comment by NewOldMax** [comment]
Hi,

you can [see](https://github.com/NewOldMax/react-material-ui-form-validator/blob/master/src/ValidationRules.jsx#L17) that `matchRegexp` function accept two parameters, so you can easily use something like `validators={['matchRegexp:^(https?|ftp):\/\/[^\s\/$.?#]+\\.[^\s]*$']}`

Every validation function, which accepts two parameters, can be used in the following way. You can create a PR for this, if you want

**Comment by kevincianfarini** [comment]
are the two parameters signified by a separating colon? the one between matchRegExp and the Regex

**Comment by NewOldMax** [comment]
You separate parameters by colon. Left part - validation function name, right part - extra parameter to validation function.

Example:
````javascript
validators={['matchRegexp:^[a-z]$', 'maxNumber:599', 'minNumber:10']}
````

**Comment by NewOldMax** [comment]
Documentation is updated
