### ISSUE TITLE
_ValidationRules2.default[name] is not a function

### ISSUE THREAD

**Issue by GonzoAS** [NewOldMax/react-material-ui-form-validator#172]
![Captura de Pantalla 2022-06-15 a la(s) 9 41 12](https://user-images.githubusercontent.com/48097997/173855430-ebe3404a-4ee2-4946-b70b-1021757b5993.png)

**Comment by NewOldMax** [comment]
please, create a snippet with your error [here](https://codesandbox.io/s/new)

**Comment by GonzoAS** [comment]
wow, great time response, but I found my error, so stupid sorry...

in my code I had:
validators={[
                            'required',
                            'checkRegexp:^[a-zA-ZñÑÁÉÍÓÚáéíóúÄËÏÖÜäëïöü]+( [a-zA-ZñÑÁÉÍÓÚáéíóúÄËÏÖÜäëïöü]+)?$'
                        ]}
                        errorMessages={[
                          'Este campo es obligatorio',
                          'Caracteres invalidos'
                        ]}

the correct code:
validators={[
                            'required',
                            'matchRegexp:^[a-zA-ZñÑÁÉÍÓÚáéíóúÄËÏÖÜäëïöü]+( [a-zA-ZñÑÁÉÍÓÚáéíóúÄËÏÖÜäëïöü]+)?$'
                        ]}
                        errorMessages={[
                          'Este campo es obligatorio',
                          'Caracteres invalidos'
                        ]}

Its matchRegexp not checkRegexp. :( :)
