### ISSUE TITLE
SelectValidator causing page scroll to vanish - unable to override

### ISSUE THREAD

**Issue by Luke-S1** [NewOldMax/react-material-ui-form-validator#173]
Hello there,

The issue we are encountering is that the <SelectValidator/> component will not accept MenuProps={{disableScrollLock: true}} attribute.

This means that when the select is opened, the page shifts to the right as the portal that holds the select elements does not exceed the page height.

**Comment by NewOldMax** [comment]
@Luke-S1 Hi, try to use it as
```
SelectProps={{
    MenuProps: { disableScrollLock: true },
}}
```
SelectValidator uses TextField component so all Select related props must be passed via SelectProps

**Comment by AkshatK805** [comment]
Hi, I'm new to react-material-ui-form-validator. Can someone help me understand how to use radio buttons with react-material-ui-form-validator with an example code?

**Comment by NewOldMax** [comment]
@AkshatK805 you can check this one #65

**Comment by AkshatK805** [comment]
@NewOldMax thank you so much, it worked.
