### ISSUE TITLE
issue while using instantValidate

### ISSUE THREAD

**Issue by AkshatK805** [NewOldMax/react-material-ui-form-validator#175]
I have validations defined as 
validators={["required", "minStringLength:2"]}
errorMessages={["Please enter a User ID","User ID cannot be less than 2 characters"]}

I want to have these validations trigger at submit only.
The issue what happening if I'm keeping instantValidate as false is that if I enter just one character in textfield and then click on save button then I see the validation message "User ID cannot be less than 2 characters", but if I write the second character then the validation persists instead of disappearing cause it's validating the state on click of save button. I tried using a state variable to trigger the instantValidateState on onChange event but no luck.

Can anyone help me on this?

**Comment by NewOldMax** [comment]
@AkshatK805 Hi,

please create example with issue [here](https://codesandbox.io/s/new)

**Comment by AkshatK805** [comment]
@NewOldMax https://codesandbox.io/s/mystifying-paper-w4jjz8?file=/src/App.js
Here you can see instantValidate is false so even if I satisfy validation after typing the second character the validation doesn't go away till I click save button again but if possible I want the validation to go away after the user types the second character.

**Comment by NewOldMax** [comment]
@AkshatK805 you can reset validations manually when you need it
example https://codesandbox.io/s/kind-wilbur-1n4dtg?file=/src/App.js

**Comment by AkshatK805** [comment]
@NewOldMax but with this way validations for other fields will disappear as well, like I've added a first name field. On initial click of save button we have req validations for both fields but if I enter user id then the validation message for first name also disappears which should persist.
https://codesandbox.io/s/agitated-greider-nwjocq?file=/src/App.js

**Comment by NewOldMax** [comment]
then you can use "makeValid" function for each validated input
https://codesandbox.io/s/elated-black-td6yhs

**Comment by AkshatK805** [comment]
@NewOldMax is this the only possible solution for large forms as well? defining a ref for each form input?

**Comment by NewOldMax** [comment]
you want to have inputs instantly validated on input, but with instantValidate=false, so this is only way
