### ISSUE TITLE
SelectValidator suggestion pop-up(MenuItem) showing on top of the field(should be show just below the field)

### ISSUE THREAD

**Issue by sadashiv-sumasoft** [NewOldMax/react-material-ui-form-validator#176]
Hi guys,
I am using SelectValidator component of react-material-ui-form-validator for selecting one choice from the suggested dropdown of choices.
but when i clicked on the component the suggestion pop-up is showing on top of the field so user can not see his selection( 
 I know it is only single selection field so what he clicked would be selected but the suggestion pop-up is not consistent at one place, it is moving top or bottom side based on selection you made, if you select the last choice and again clicked on the field the suggestion pop-up is moving far top side).

I have applied below styles for it but it didn't worked for me, Any suggestion?
![SelectValidator](https://user-images.githubusercontent.com/89510166/188965238-36513b24-ba9c-4050-91e1-c3591a35461c.PNG)

**Comment by NewOldMax** [comment]
@sadashiv-sumasoft Hi,
please create component with issue [here](https://codesandbox.io/s/new)
