### ISSUE TITLE
Chrome autofill overlapping TextValidator component floating label.

### ISSUE THREAD

**Issue by sadashiv-sumasoft** [NewOldMax/react-material-ui-form-validator#178]
Hi,
I am using the TextValidator component for our react app, for login page when chrome autofill the username and password field the textvalidator floating label does not go up as browser onFocus event is not trigger.

I am not sure as this problem is associated with Textvalidator component or not but i am here for getting any idea about how can i tackle this problem.

Any suggestion will be appreciate.
Thank you.

**Comment by NewOldMax** [comment]
mui issue
https://github.com/mui/material-ui/issues/14427
