### ISSUE TITLE
minStringlength,maxStringlength not detecting changes while value pre setted using state

### ISSUE THREAD

**Issue by kkg0** [NewOldMax/react-material-ui-form-validator#181]

**Comment by kkg0** [comment]
errorMessages={[
                  "-",
                  "---",
                  "----",
                  "-----",
                ]}
                validators={[
                  "required",
                  "isNumber",
                  "minStringLength: 10",
                  "maxStringLength: 10",
                ]}

**Comment by NewOldMax** [comment]
Please describe your issue and provide example with issue [here](https://codesandbox.io/s/react-new)

**Comment by kkg0** [comment]
> Please describe your issue and provide example with issue [here](https://codesandbox.io/s/react-new)

<TextField
                inputProps={{
                  pattern: "[0-9]*",
                  maxLength: "10",
                }}
                type="tel"
                name="mobileno"
                id="standard-basic1"
                value={props.state.mobileno || ""}
                onChange={props.handleChange}
                errorMessages={[
                  "મોબાઇલ નંબર દાખલ કરો",
                  "માન્ય મોબાઇલ નંબર દાખલ કરો",
                  "માન્ય મોબાઇલ નંબર દાખલ કરો",
                  "માન્ય મોબાઇલ નંબર દાખલ કરો",
                ]}
                label="મોબાઇલ નંબર *"
                validators={[
                  "required",
                  "isNumber",
                  "minStringLength: 10",
                  "maxStringLength: 10",
                ]}
              />

After setting the value using props still show error and when i change using typing it fixes

**Comment by kkg0** [comment]
Solved the issue by passing value in String method like value={String(props.state.mobileno)} instead of value={props.state.mobileno}
