### ISSUE TITLE
How to send RegExp flags (g,i,m) with matchRegexp?

### ISSUE THREAD

**Issue by proteye** [NewOldMax/react-material-ui-form-validator#20]
Hello.
How to send RegExp flags (g,i,m) with matchRegexp?
'matchRegexp:/^([0-9]{4}\\s*){4}$/gi' convert to RegExp -  /\/^([0-9]{4}\s*){4}$\/gi/

**Comment by NewOldMax** [comment]
Hi
Currently you can't do that. But you can create you own ValidationRule. Look at Readme for example.
