### ISSUE TITLE
Internet Explorer 10 and below throws error - unable to get property 'attachToForm' of null reference or undefined

### ISSUE THREAD

**Issue by rashmiap** [NewOldMax/react-material-ui-form-validator#21]
This plugin works fine in Chrome, Safari and other browsers. However in Internet Explorer 10 and below throws this error - 'unable to get property attachToForm of undefined' because of which the whole application breaks.

![image](https://user-images.githubusercontent.com/29939427/27896758-a0783ef6-6239-11e7-80bb-9a6307c4cf38.png)

**Comment by NewOldMax** [comment]
Hi,

Currently this library doesn't support IE10 and below, because they lose context when you use class inheritance. It's a known issue for many libraries. If you can do a PR to fix this, you're welcome.

**Comment by rashmiap** [comment]
Damn you internet explorer 😣
Thanks for your help!
