### ISSUE TITLE
'required' broken?

### ISSUE THREAD

**Issue by estaub** [NewOldMax/react-material-ui-form-validator#24]
The `required` validator isn't working for me, and looks broken in the code.  AFAICT `IncludeRequired` is never set anywhere, and therefore the `required` validator is never invoked.

**Comment by NewOldMax** [comment]
Can you show your code example? React/browser/material-ui versions and your expected behavior

**Comment by estaub** [comment]
I'm an idiot, nevermind.  Delete issue if desired.

BTW, I think this lib is very underappreciated, simply because people don't know about it.  
Nice job!
