### ISSUE TITLE
reset() is not a function

### ISSUE THREAD

**Issue by vineet-agrawal96** [NewOldMax/react-material-ui-form-validator#25]
Hi
I'm using react-material-ui-form-validator for my project. onChange event I want to reset Validator form for this I'm using following code:
                                                this.refs.paymentForm.reset()
but getting following error:
                                   Uncaught TypeError: this.refs.paymentForm.reset is not a function

Please help.
Thanks

**Comment by NewOldMax** [comment]
Hi,
As you can see in [source code](https://github.com/NewOldMax/react-material-ui-form-validator/blob/master/src/ValidatorForm.jsx) there is no `reset` function, I don't know, why you tried ti use non-existing function.
Can you tell more about your use case?

**Comment by NewOldMax** [comment]
When you use this library, your form must be [controlled](https://facebook.github.io/react/docs/forms.html#controlled-components), so native `reset` function won't work. You should handle it manually from your code.
