### ISSUE TITLE
'required' validation doesn't support onBlur event for TextValidator

### ISSUE THREAD

**Issue by nikhil4326** [NewOldMax/react-material-ui-form-validator#27]
'required' field validation only worked with submit button not with onblur event.
To make it Work, other way I found is to add custom validation rule to validateForm. 
 Without using above workaround Is there any way to use 'required' validation with onblur event in textField?

**Comment by NewOldMax** [comment]
Hi,

you can just put `true` as second parameter to `validate` function
````javascript
handleBlur(event) {
    this.refs[event.target.name].validate(event.target.value, true);
}
````
and `required` validation will work with `onBlur` event
