### ISSUE TITLE
material-ui v1 support

### ISSUE THREAD

**Issue by NewOldMax** [NewOldMax/react-material-ui-form-validator#28]
- [x] text field
- [x] select field
- [ ] autocomplete *(currently not supported by matereial-ui v1 as built-in component)*
- [ ] datepicker/timepicker *(currently not supported by matereial-ui v1)* [example with material-ui-pickers](https://github.com/NewOldMax/react-material-ui-form-validator/wiki/Material-ui-v1-datepickers-example)

**Comment by setvik** [comment]
Awesome. Been looking forward to support for v1.

Is it possible to publish this to npm? or do you know if it's possible to npm install from this branch?
I tried
```
npm i https://github.com/NewOldMax/react-material-ui-form-validator#1.0.0-beta.4 --save
```

but it installed a react-material-ui-form-validator directory without a lib subdirectory.

**Comment by NewOldMax** [comment]
Hi

Please check Wiki page for instructions

**Comment by setvik** [comment]
Thanks! I completely missed the installation line at the top.

**Comment by lucasbento** [comment]
Shouldn't `SelectField` component work just by changing [this import](https://github.com/NewOldMax/react-material-ui-form-validator/blob/master/src/SelectValidator.jsx#L3) to `import SelectField from 'material-ui/Select';`?

**Comment by NewOldMax** [comment]
@lucasbento  As I see in current docs, `Select` requires `FormControl` to show error state.

From docs:
````javascript
        <FormControl className={classes.formControl} error>
          <InputLabel htmlFor="name-error">Name</InputLabel>
          <Select
            value={this.state.name}
            onChange={this.handleChange('name')}
            renderValue={value => `⚠️  - ${value}`}
            input={<Input id="name-error" />}
          >
            <MenuItem value="">
              <em>None</em>
            </MenuItem>
            <MenuItem value="hai">Hai</MenuItem>
            <MenuItem value="olivier">Olivier</MenuItem>
            <MenuItem value="kevin">Kevin</MenuItem>
          </Select>
          <FormHelperText>Error</FormHelperText>
        </FormControl>
````

**Comment by tomscholz** [comment]
> <= 1.x - supports material-ui <= 0.x
> => 2.x - supports material-ui >= 1.x (experimental support, you can install it by npm i react-material-ui-form-validator@next)
> => 1.0.1 - supports React 16

This means that `2.0.0-beta.1` supports react 16, right?

**Comment by NewOldMax** [comment]
@tomscholz yes, it supports

**Comment by tomscholz** [comment]
I am currently trying to add validation to a form that is built using material-ui components. I have it working but the problem is that when I add the Validation with the components given by this package I get some errors. Can anyone help me out? :)

```
Warning: Stateless function components cannot be given refs. Attempts to access this ref will fail.

Check the render method of `TextValidator`.
    in TextField (created by TextValidator)
    in TextValidator (created by Login)
    in form (created by ValidatorForm)
    in ValidatorForm (created by Login)
    in Login (created by Route)
    in Route (created by Public)
    in Public (created by App)
    in div (created by MainLayout)
    in MainLayout (created by withStyles(MainLayout))
    in withStyles(MainLayout) (created by App)
    in Switch (created by App)
    in div (created by App)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by App)
    in App (created by ReactMeteorDataComponent)
    in ReactMeteorDataComponent
    in MuiThemeProvider

Uncaught TypeError: _ValidationRules2.default[name] is not a function
    at ValidatorForm.getValidator

Uncaught TypeError: _ValidationRules2.default[name] is not a function
    at ValidatorForm.getValidator
```

This is my code:
```
import React from "react"; // 16.0.0

import Button from "material-ui/Button"; // 1.0.0-beta.16

import { ValidatorForm } from 'react-form-validator-core'; // 0.1.1
import { TextValidator } from 'react-material-ui-form-validator'; // 2.0.0-beta.1

class Login extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      data: {}
    };
    this.handleValue = this.handleValue.bind(this);
    this.handleBlur = this.handleBlur.bind(this);
    this.handleSubmit = this.handleSubmit.bind(this);
  }

  handleValue(event) {
    const {data} = this.state.data;
    data[event.target.name] = event.target.value;
    this.setState({data});
  }

  handleSubmit() {
    /* login logic */
  }
  
  render() {
    const { data } = this.state;

    return (
      <ValidatorForm
        onSubmit={this.handleSubmit}
        onError={errors => console.log(errors)}
      >
        <TextValidator
          id="email"
          name="email"
          label="Email"
          margin="normal"
          value={data.email}
          onChange={this.handleValue}
          validators={["required', 'isEmail"]}
          errorMessages={["Need an email address here.', 'Incorrect email address!"]}
        />
        <TextValidator
          id="password"
          name="password"
          label="Password"
          type="password"
          margin="normal"
          value={data.password}
          onChange={this.handleValue}
          validators={['isPasswordMatch', 'required']}
          errorMessages={['This field is required']}
        />
        <Button
          type="submit"
          color="primary"
          raised
        >
          Log In
        </Button>
      </ValidatorForm>
    );
  }
}

export default Login;
```

**Comment by NewOldMax** [comment]
@tomscholz try with `2.0.0-beta.2`, should be fixed

**Comment by tomscholz** [comment]
Still getting the same error :(

**Comment by NewOldMax** [comment]
It's really weird, because for me it's fixed after update

**Comment by tomscholz** [comment]
pingng

**Comment by NewOldMax** [comment]
I see in your code `isPasswordMatch`. Did you defined it somewhere?

**Comment by tomscholz** [comment]
whoops that wasn't supposed to be there. But still getting https://github.com/NewOldMax/react-material-ui-form-validator/issues/28#issuecomment-336408061 . Thanks for pointing that out though :)

**Comment by NewOldMax** [comment]
@tomscholz there is a typo
````javascript
validators={["required', 'isEmail"]}
````
should be
````javascript
validators={['required', 'isEmail']} // fix quotes
````

**Comment by tomscholz** [comment]
Nice thanks :) Only thing left is that I now get `Uncaught TypeError: Cannot set property 'password' of undefined`

**Comment by NewOldMax** [comment]
Problem with your `handleValue` function
should be `const { data } = this.state`, not `const { data } = this.state.data`

**Comment by setvik** [comment]
Trying out SelectValidator as follows:
`<SelectValidator name="gradeLevelId"
        value={defaults.gradeLevelId}
        onChange={props.handleChange('gradeLevelId')}
        formControl={<FormControl />}
        validators={['required']}
        errorMessages={['required field']}
        inputLabel={<InputLabel>Select your grade range</InputLabel>}
      >`

but getting the following error:

`Warning: Failed prop type: Invalid prop `formControl` of type `object` supplied to `SelectValidator`, expected `function`.`

Thoughts?

**Comment by NewOldMax** [comment]
@setvik try to pass
````
formControl={FormControl}
````

**Comment by NewOldMax** [comment]
And for label create something like this
````
const Label = () => <InputLabel>Select your grade range</InputLabel>;

inputLabel={Label}
````
It's not a perfect solution, but still I wait for stable release of v1

**Comment by setvik** [comment]
@NewOldMax Thanks! That worked. One last thing I need to figure out is how to get it to be fullWidth. I tried adding fullWidth to both SelectValidator and via className={classes...} but neither worked. Is there a way i can pass FullWidth through to FormControl?

**Comment by NewOldMax** [comment]
@setvik try to use something like
````javascript
const CustomControl = () => <FormControl yourProps />;

formControl={CustomControl}
````

**Comment by setvik** [comment]
awesome. thanks so much!

**Comment by tomscholz** [comment]
This may the wrong place to ask, but how can I get a reference to the generated <input> dom element? When I try to access the value of the input element with `this.password.value()`, the value is `undefined`.

```jsx
 <TextValidator
  ref={(password) => { this.password = password; }}
  id="password"
  name="password"
  label="Password"
  type="password"
  margin="normal"
  fullWidth
  value={data.password || ""}
  onChange={this.handleValue}
  validators={["required"]}
  errorMessages={["This field is required"]}
/>
```

**Comment by NewOldMax** [comment]
@tomscholz there shouldn't be a problem with it. Maybe something wrong with your `render` function, or you want to take your `value` in wrong place.
Btw you already have it in `data.password`

**Comment by setvik** [comment]
@NewOldMax Anything special i need to do to get validation working with <SelectValidator native> (i.e. the "native" attribute that tells Material UI to render the select using a native <select /> element)?

The bug I'm seeing is that even if a value is selected, the "required" validator still errors and the form can't be submitted.

**Comment by SyedHaris94** [comment]
./node_modules/react-material-ui-form-validator/lib/AutoCompleteValidator.js
Module not found: Can't resolve 'react-autosuggest' in 'F:\web-panel\node_modules\react-material-ui-form-validator\lib'

i use beta version and got this error

**Comment by NewOldMax** [comment]
@SyedHaris94 please check closed issues, you are not alone with this error

**Comment by SyedHaris94** [comment]
how can i resolve this error need help..

**Comment by NewOldMax** [comment]
Just install 'react-autosuggest'

**Comment by SyedHaris94** [comment]
already got installed but still got same error.

**Comment by SyedHaris94** [comment]
![df](https://user-images.githubusercontent.com/16894018/32914752-78eaa80c-cb38-11e7-9fc2-6ff1fea2597a.PNG)

**Comment by NewOldMax** [comment]
@SyedHaris94 please create new issue for your problems, lets keep this one clear

**Comment by pietrofxq** [comment]
Is it possible to not depend on autosuggest? I wouldn't like to install as dependency something I'm not using

**Comment by NewOldMax** [comment]
It's possible in future release, when support of Autocomplete will be removed

**Comment by NewOldMax** [comment]
Autocomplete validator has been removed in beta4

**Comment by SysOpsNet** [comment]
I wonder how can I make a textfield multiline? I'm using @next.

**Comment by NewOldMax** [comment]
@SysOpsNet what about setting `multiline` prop?

**Comment by mlake** [comment]
1.0.0-rc is out and has major breaking changes :/ ...

**Comment by NewOldMax** [comment]
2.0.0-beta.10 is here with `@material-ui/core` support

**Comment by pavanshinde47** [comment]
I have just installed react-material-ui-form-validator": "^2.0.0-beta.10 abd getting error shown in the image below. I have react 16.3 and material 0x and 1x both, I am migrating to v1. Let me know how to fix the error.

http://prntscr.com/jj0ef7

**Comment by NewOldMax** [comment]
@pavanshinde47 try to reproduce your issue [here](https://codesandbox.io/s/p52x38v22m)

**Comment by RudmanMario** [comment]
I'm having a problem with `SelectValidator`. I'm using material-ui 1.0 and react-material-ui-form-validator 2.0.0-beta.10. The FormControl and InputLabel that I pass as props are not used in `SelectValidator` component. This is my custom select component:
```
render() {
        const {classes, disabled, value, name, selectArray, optionProp, optionKey, label, onSelectChange} = this.props;

        const CustomControl = () => <FormControl className={classes.formControl} disabled={disabled} fullWidth="true" />;

        const InputLabel = () => <InputLabel htmlFor={name + "-helper"}>{label}</InputLabel>;

        return (
            <SelectValidator
                name={name}
                value={value ? value[optionKey]: ""}
                onChange={(evt) => onSelectChange(evt, optionKey)}
                formControl={CustomControl}
                validators={['required']}
                errorMessages={['required field']}
                inputLabel={InputLabel}
                input={<Input name={name} id={name + "-helper"} />}
            >
                {selectArray.map(item => {
                    return (
                        <MenuItem key={item[optionKey]} value={item[optionKey]}>{item[optionProp]}</MenuItem>
                    )
                })}
            </SelectValidator>
        )
    }
```
Am I doing something wrong?

**Comment by NewOldMax** [comment]
Please check examples at wiki page

вс, 20 мая 2018, 19:16 RudmanMario <notifications@github.com>:

**Comment by RudmanMario** [comment]
Thank you for you fast reply. Now it's working but I still don't know how to set `FormControl `props. I need the `FormControl` to have fullWidth prop set. Can you help me with that?

**Comment by RudmanMario** [comment]
Works great, thank you!

**Comment by NewOldMax** [comment]
2.0.0 is released
