### ISSUE TITLE
Regex pattern or min,max number not working

### ISSUE THREAD

**Issue by nikhil4326** [NewOldMax/react-material-ui-form-validator#29]
I was trying to add validation for zipcode in textvalidator.
Like Below
<TextValidator
                      ref='zipCode'
                      hintText="ex. 00000"
                      name='zipCode'
                      onBlur={this.handleBlur}
                      onChange={this.onChange}
                      value={this.state.zipCode}
                      validators={['required','matchRegexp:^\d{5}$']}
                      errorMessages={[ 'Field is required','Zip Code should have 5 digits']}/>
OR
<TextValidator
                      ref='zipCode'
                      hintText="ex. 00000"
                      name='zipCode'
                      onBlur={this.handleBlur}
                      onChange={this.onChange}
                      value={this.state.zipCode}
                      validators={['required','minNumber:5', 'maxNumber:5']}
                      errorMessages={['Field is required','Zip Code should have 5 digits','Zip Code should have 5 digits']}/>

Both the ways are not working. Please help me on this issue

**Comment by NewOldMax** [comment]
Hi

Just use ``'matchRegexp:^\\d{5}$'``, you should escape ``\``
`minNumber` and `maxNumber` are validating value, not count of digits
