### ISSUE TITLE
Form is still submitted if validation fails

### ISSUE THREAD

**Issue by Cristy94** [NewOldMax/react-material-ui-form-validator#32]
How can I disable form submission if there are validation errors?

**Comment by NewOldMax** [comment]
You can use [onError](https://github.com/NewOldMax/react-form-validator-core#validatorform) callback

**Comment by Cristy94** [comment]
Oh, my bad, I forgot to remove the original `onClick` submit from the submit button, so the form was submitted even though validation failed.
