### ISSUE TITLE
minNumber validater validates input is correct when 2 characters set, regardless of value specified

### ISSUE THREAD

**Issue by DocCaliban** [NewOldMax/react-material-ui-form-validator#34]
Not sure if anyone else is seeing this, but it appears that when I use the validator in the below example, it validate the password after 2 characters rather than 6.
          <TextValidator
            type="password"
            onChange={this.handleChange}
            name="password"
            value={formData.password}
            validators={['required','minNumber:6']}
            errorMessages={['This field is required.','Password must be at least 6 characters long.']}
            floatingLabelText='Choose a Password'
          />

**Comment by DocCaliban** [comment]
Apparently I didn't not fully understand the implementation. minNumber is a numeric test

**Comment by NewOldMax** [comment]
@DocCaliban soon in new release of  `react-form-validator-core` package will be builtin `minLenght` and `maxLength` validators

**Comment by nmaaruf** [comment]
instead of minNumber:6 you can user minNumber:111111 will work

['required', 'isNumber', 'minNumber:111111111111']
