### ISSUE TITLE
Module not found: Can't resolve 'react-autosuggest' in 'D:\study\rc-admin\node_modules\react-material-ui-form-validator\lib'

### ISSUE THREAD

**Issue by djkloop** [NewOldMax/react-material-ui-form-validator#35]
- {
  "name": "rc-admin",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "autoprefixer": "7.1.6",
    "axios": "^0.17.0",
    "babel-core": "6.26.0",
    "babel-eslint": "7.2.3",
    "babel-jest": "20.0.3",
    "babel-loader": "7.1.2",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-react-app": "^3.1.0",
    "babel-runtime": "6.26.0",
    "body-parser": "^1.18.2",
    "case-sensitive-paths-webpack-plugin": "2.1.1",
    "chalk": "1.1.3",
    "cookie-parser": "^1.4.3",
    "css-loader": "0.28.7",
    "dotenv": "4.0.0",
    "echarts": "^3.7.2",
    "eslint": "4.10.0",
    "eslint-config-react-app": "^2.0.1",
    "eslint-loader": "1.9.0",
    "eslint-plugin-flowtype": "2.39.1",
    "eslint-plugin-import": "2.8.0",
    "eslint-plugin-jsx-a11y": "5.1.1",
    "eslint-plugin-react": "7.4.0",
    "express": "^4.16.2",
    "extract-text-webpack-plugin": "3.0.2",
    "file-loader": "1.1.5",
    "fs-extra": "3.0.1",
    "html-webpack-plugin": "2.29.0",
    "jest": "20.0.4",
    "lodash": "^4.17.4",
    "material-ui": "next",
    "material-ui-icons": "^1.0.0-beta.17",
    "mongoose": "^4.12.6",
    "node-sass": "^4.5.3",
    "nodemon": "^1.12.1",
    "object-assign": "4.1.1",
    "postcss-flexbugs-fixes": "3.2.0",
    "postcss-loader": "2.0.8",
    "promise": "8.0.1",
    "raf": "3.4.0",
    "react": "^16.0.0",
    "react-dev-utils": "^4.2.1",
    "react-dom": "^16.0.0",
    "react-material-ui-form-validator": "^2.0.0-beta.2",
    "react-redux": "^5.0.6",
    "react-router-dom": "^4.2.2",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0",
    "sass-loader": "^6.0.6",
    "style-loader": "0.19.0",
    "sw-precache-webpack-plugin": "0.11.4",
    "typeface-roboto": "^0.0.43",
    "url-loader": "0.6.2",
    "webpack": "3.8.1",
    "webpack-dev-server": "2.9.3",
    "webpack-manifest-plugin": "1.3.2",
    "whatwg-fetch": "2.0.3"
  },
  "scripts": {
    "start": "node scripts/start.js",
    "build": "node scripts/build.js",
    "server:node": "nodemon server/server.js"
  },
  "jest": {
    "collectCoverageFrom": [
      "src/**/*.{js,jsx,mjs}"
    ],
    "setupFiles": [
      "<rootDir>/config/polyfills.js"
    ],
    "testMatch": [
      "<rootDir>/src/**/__tests__/**/*.{js,jsx,mjs}",
      "<rootDir>/src/**/?(*.)(spec|test).{js,jsx,mjs}"
    ],
    "testEnvironment": "node",
    "testURL": "http://localhost",
    "transform": {
      "^.+\\.(js|jsx|mjs)$": "<rootDir>/node_modules/babel-jest",
      "^.+\\.css$": "<rootDir>/config/jest/cssTransform.js",
      "^(?!.*\\.(js|jsx|mjs|css|json)$)": "<rootDir>/config/jest/fileTransform.js"
    },
    "transformIgnorePatterns": [
      "[/\\\\]node_modules[/\\\\].+\\.(js|jsx|mjs)$"
    ],
    "moduleNameMapper": {
      "^react-native$": "react-native-web"
    },
    "moduleFileExtensions": [
      "web.js",
      "mjs",
      "js",
      "json",
      "web.jsx",
      "jsx",
      "node"
    ]
  },
  "babel": {
    "presets": [
      "react-app"
    ],
    "plugins": [
      "transform-decorators-legacy"
    ]
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "proxy": "http://localhost:5168"
}

![260hyvw f3n naz489b oku](https://user-images.githubusercontent.com/21050914/32833536-2945c9ca-ca3a-11e7-8010-b087c2fb9bae.png)
![j 0 d2x vyg xty9cma zpy](https://user-images.githubusercontent.com/21050914/32833613-5a28a0c6-ca3a-11e7-8456-8064105a430a.png)
![k g6 9jswn 2ir 0kaw0 8](https://user-images.githubusercontent.com/21050914/32833632-6c0f308e-ca3a-11e7-9214-82720fe46c7b.png)

**Comment by NewOldMax** [comment]
You need to install `react-autosuggest` as dependency for material-ui v1 and this library

**Comment by NewOldMax** [comment]
And you installed beta release with v1 support and use component with `floatingLabelText`, it's previous version of material-ui

**Comment by djkloop** [comment]
@NewOldMax thx! Hope to have more modules later~

**Comment by estaub** [comment]
@NewOldMax you might want to put the react-autosuggest depend in the readme.  It's surprising that it's a dependency - my expectation was that it was a bug.  react-autosuggest is no longer a dependency of material-ui, probably because it has a viable competitor now, [downshift](https://github.com/paypal/downshift).  See https://material-ui-next.com/demos/autocomplete/.

**Comment by NewOldMax** [comment]
@estaub you're right.
Anyways `Autocomplete` validator should be redesigned in some universal way (to not separate components for every Autocomplete implementation), but now I don't see nice solution to do this, because they have very different api. Maybe better solution is remove Autocomplete validator and let user create his own by extending `ValidatorComponent`
