### ISSUE TITLE
material-ui v1

### ISSUE THREAD

**Issue by SyedHaris94** [NewOldMax/react-material-ui-form-validator#37]
./node_modules/react-material-ui-form-validator/lib/AutoCompleteValidator.js
Module not found: Can't resolve 'material-ui/AutoComplete'

got this error after installing react-material-ui-form-validator@next

**Comment by NewOldMax** [comment]
here is working example for you https://codesandbox.io/s/p52x38v22m
as I said before, check your environment, somewhere you have problem

**Comment by SyedHaris94** [comment]
thanks @NewOldMax
