### ISSUE TITLE
React 16 depend pinned at 16.0.0 - intended or bug?

### ISSUE THREAD

**Issue by estaub** [NewOldMax/react-material-ui-form-validator#38]
In package.json, should 

    "react": "^15.0.0 || 16.0.0",
    "react-dom": "^15.0.0 || 16.0.0",

perhaps read

    "react": "^15.0.0 || ^16.0.0",
    "react-dom": "^15.0.0 || ^16.0.0",

?

**Comment by NewOldMax** [comment]
Can you test it with latest `react` version? I can't do it for now. If it works, I will upgrade it later

**Comment by NewOldMax** [comment]
Fixed in 1.0.3
