### ISSUE TITLE
Required validation not working

### ISSUE THREAD

**Issue by joscalv** [NewOldMax/react-material-ui-form-validator#39]
Hi

I have a trouble with the library. I am not able to make work the required validation , it only works when the form is submited.

In the eample the email validation is working but the required not.

Thanks

```
<TextValidator
                        floatingLabelText="prueba email"
                        onChange={this.handleChange}
                        name="email"
                        type={'text'}
                        validators={['required', 'isEmail']}
                        errorMessages={['this field is required', 'email is not valid']}
                        value={this.state['email']}
                   />
```

**Comment by NewOldMax** [comment]
`required` validator works only after submitting, it's by design and more friendly for user to see clear form at start, and validation messages after submit. If you want to show `required` error without submit, you should call it manually
See #27 for more details
