### ISSUE TITLE
Question: Adding rule to compare two fields

### ISSUE THREAD

**Issue by codesandtags** [NewOldMax/react-material-ui-form-validator#4]
Hi dude!

This validator is pretty useful!. I would like to know how can I create/add a rule which compares two fields. I was reading the source code and debugging but I think at this moment, is not possible.

Thanks in advance for your time!

Cheers.

**Comment by NewOldMax** [comment]
Hi, @codesandtags 
You can see an example with custom rules in readme (second code example in [usage](https://github.com/NewOldMax/react-material-ui-form-validator#usage) section, look at `addValidationRule`)

**Comment by codesandtags** [comment]
Thank you! I have tried using that implementation way!. However for any reason, I'm having only access to the ValidatorForm scope/functions. Here you will find an axample :) 

![image](https://cloud.githubusercontent.com/assets/5404833/24408094/59423e74-1392-11e7-87e6-4bb3cae31f6e.png)

**Comment by NewOldMax** [comment]
You should use `=>` function to get access to correct `this`
````javascript
ValidatorForm.addValidationRule('isPasswordMatch', (value) => {
    if (value !== this.state.user.password) {
        return false;
    }
    return true;
});
````

**Comment by NewOldMax** [comment]
Or you can create:
````javascript
function mySuperFunc(value) {
    if (value !== this.state.user.password) {
        return false;
    }
    return true;
}

ValidatorForm.addValidationRule('isPasswordMatch', mySuperFunc.bind(this));

````

**Comment by codesandtags** [comment]
Thanksl @NewOldMax ! The second one has worked well for me!. 

You rock! :)

**Comment by Standin-Alone** [comment]
how to compare values with nested state
