### ISSUE TITLE
Try to add new validation rule using react-material-ui-form-validator 2.0.0-beta.2

### ISSUE THREAD

**Issue by kushaljain03** [NewOldMax/react-material-ui-form-validator#41]
I was trying to add new validation rule. I am using react "material-ui": "^1.0.0-beta.21",

Here is the code by which I try to add new rule but got error

`ValidatorForm.addValidationRule('isCanRequired', (value) => {
        if(this.state.canSameAccount){
          if(value==null || value==="" || value===undefined)
            return false;
        }
        return true;
    });`

I add this code in componentWillMount but its not working.
Here is the error screenshot when I click on submit button
[https://i.stack.imgur.com/cBJSv.png](url)

**Comment by NewOldMax** [comment]
Are you using `react-material` or `material-ui`? It's important because this package can be used only for `material-ui`

**Comment by kushaljain03** [comment]
I am using material-ui package

**Comment by NewOldMax** [comment]
Well, can you show you component?

**Comment by kushaljain03** [comment]
yes,
you can check this link
https://stackoverflow.com/questions/47406412/try-to-add-new-validation-rule-in-reactjs-material

**Comment by NewOldMax** [comment]
Can you show more? Because it's working in main case

**Comment by kushaljain03** [comment]
You can check this code.
And i also share my package.json

{
  "name": "signup",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "material-ui": "^1.0.0-beta.21",
    "react": "16.0.0",
    "react-dom": "16.0.0",
    "react-form-validator-core": "^0.1.1",
    "react-material-ui-form-validator": "^2.0.0-beta.2",
    "react-scripts": "1.0.17"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}



import React from 'react';
import Button from 'material-ui/Button';
import { ValidatorForm } from 'react-form-validator-core';
import { TextValidator} from 'react-material-ui-form-validator';

class MyForm extends React.Component {

    constructor(props) {
        super(props);
        this.state = {email:""};
        this.handleChange = this.handleChange.bind(this);
    }

    handleChange(event) {
        const email = event.target.value;
        this.setState({ email });
    }

    handleSubmit() {
        // your submit logic
    }

    render() {
        const { email } = this.state;
        return (
            <ValidatorForm
                ref="form"
                onSubmit={this.handleSubmit}
                onError={errors => console.log(errors)}
            >
                <TextValidator
                    floatingLabelText="Email"
                    onChange={this.handleChange}
                    name="email"
                    value={email}
                    validators={['required']}
                    errorMessages={['this field is required', 'email is not valid']}
                />
                <Button type="submit" />
            </ValidatorForm>
        );
    }
}

export default MyForm;

**Comment by NewOldMax** [comment]
If you are using `beta` release (which isn't ready yet, it's beta 😄), you can use builtin `ValidatorForm`
````javascript
import { TextValidator, ValidatorForm } from 'react-material-ui-form-validator';
````

**Comment by kushaljain03** [comment]
In which version I can add new validation rules ?

**Comment by NewOldMax** [comment]
You can add it here, if use ValidatorForm from this package

**Comment by kushaljain03** [comment]
If you look at the componentWillMount method in which I used ValidatorForm to add new rule but it's not working. 

From which package ? Can you write code sinppet

**Comment by NewOldMax** [comment]
I write already
````javascript
import { TextValidator, ValidatorForm } from 'react-material-ui-form-validator';
````
you should import ValidatorForm  from react-material-ui-form-validator, not from react-form-validator-core

**Comment by kushaljain03** [comment]
Ok, I will try out this.
