### ISSUE TITLE
How to add maxLength attribute in TextValidator Component

### ISSUE THREAD

**Issue by kushaljain03** [NewOldMax/react-material-ui-form-validator#43]
I am using beta version of react-material-ui-form-validator. I have this component

`<TextValidator floatinglabeltext="First Name" fullWidth 
                  name="firstName" value={this.state.firstName}
                  validators={['required']}
                  errorMessages={['Please enter your firstname']}
                  label="Enter First Name*" onChange={this.handleChange('firstName')} />`

and I want to add maxLength attribute into it. How can I add into it ?

**Comment by NewOldMax** [comment]
You can use `inputProps` prop, see [this](https://material-ui-next.com/demos/text-fields/#components)
````javascript
<TextValidator
    name="firstName"
    value={this.state.firstName}
    validators={['required']}
    errorMessages={['Please enter your firstname']}
    label="Enter First Name*"
    onChange={this.handleChange('firstName')}
    inputProps={{ maxLength: 10 }}
/>
````
