### ISSUE TITLE
Reset the form

### ISSUE THREAD

**Issue by johnmesh** [NewOldMax/react-material-ui-form-validator#44]
how can i reset the form on button click after displaying the error messages?

**Comment by NewOldMax** [comment]
Because this lib requires controlled components, you should implement it manually. Just reset your form state.
Example:
````javascript
onResetClick() {
  const defaultFormState = {
      fieldName: '',
      anotherFieldName: '',  
  };
  this.setState({ form: defaultFormState });
}
...
<button onClick={this.onResetClick}>reset form</button>
````

**Comment by johnmesh** [comment]
i have this form,i am able to reset the input data,but the error messages
are still showing.Please help.

**Comment by NewOldMax** [comment]
It works, check this example 
https://codesandbox.io/s/4816j6y1vx

**Comment by johnmesh** [comment]
i want such that,when the form data is reset,all the error messages
disappears

**Comment by NewOldMax** [comment]
Check code of example I given, it just works without problems

**Comment by johnmesh** [comment]
Yes it works,but when you click a button of type submit and then try and
reset the form,the errors does not go away.Check the code example,i have
incorporated a few modifications.

**Comment by johnmesh** [comment]
https://codesandbox.io/s/o925ln6wk6

**Comment by johnmesh** [comment]
Here is the scenario,try cliking the submit button without inputing any
data,then try to reset the form.You will see that the error message never
goes away

**Comment by NewOldMax** [comment]
As a workaround you try use this https://codesandbox.io/s/92w9pz0xr4

**Comment by johnmesh** [comment]
Awesome,it worked.Thanks a lot

**Comment by johnmesh** [comment]
Hello,

is it possible to disable the input *TextValidator *or make it just a
readonly?

**Comment by NewOldMax** [comment]
````javascript
<TextValidator
   disabled={true}
/>
````
should work

**Comment by NewOldMax** [comment]
@johnmesh now reset validation messages feature works out of box with [react-form-validator-core 0.3.0](https://github.com/NewOldMax/react-form-validator-core/releases/tag/0.3.0)
