### ISSUE TITLE
_ValidationRules2.default[name] Error when using custom validator

### ISSUE THREAD

**Issue by grudus** [NewOldMax/react-material-ui-form-validator#45]
Hi,
Error occurs when you try to type something in `TextValidator` with custom validator 
(it even happen in project homepage when you write any letter in 'confirm password' field in 'Custom rules') 

I'm using
    "react": "16.2.0",
    "material-ui": "0.20.0",
    "react-material-ui-form-validator": "1.0.4",

![image](https://user-images.githubusercontent.com/18220458/34423078-011bc484-ec1a-11e7-9d94-1d4d85d72816.png)

**Comment by metractive** [comment]
+1

**Comment by metractive** [comment]
The same error happens with some validation types:
- minStringLength
- maxStringLength
- isString
- Custom Validation Rules

He gives me this error:
```javascript
TypeError: _ValidationRules2.default[name] is not a function
```

**Comment by NewOldMax** [comment]
Thanks for reporting. Unfortunately I can't check it this year. Try to use old version of `react-form-validator-core` for now

**Comment by metractive** [comment]
@NewOldMax I'll check if it works with the old version and report it here. Thank you for the quick response.

**Comment by metractive** [comment]
I've tried to use version 0.1.0 and 0.2.0, but no success.
I'll check if I can help with something. Thank you @NewOldMax

**Comment by NewOldMax** [comment]
@grudus @metractive fixed in 1.0.5

**Comment by aamping** [comment]
what about for version 2.X? using Material-ui Next...

Thanks

**Comment by NewOldMax** [comment]
@aamping custom rules in 2.X works as well
But
- minStringLength
- maxStringLength
- isString
still doesn't exist

**Comment by muhammadtalha-13** [comment]
@NewOldMax any idea when minStringLength will be supported?

**Comment by NewOldMax** [comment]
@muhammadtalha-13  It should be in latest version

**Comment by muhammadtalha-13** [comment]
@NewOldMax yes just checked in another issue that it is solved in beta-4. Maybe close this issue?

**Comment by NewOldMax** [comment]
It's closed already

**Comment by siddharthjain123** [comment]
@NewOldMax Getting error _ValidationRules2.default[name] is not a function

with version "react-material-ui-form-validator": "1.1.0"

**Comment by NewOldMax** [comment]
@siddharthjain123 please, create a snippet with your error [here](https://codesandbox.io/s/r52kqrjvqp)

**Comment by ianitsky** [comment]
Here.

I created a snippet with this issue:


https://codesandbox.io/s/kk72lxq9n7

**Comment by GonzoAS** [comment]
hello, is there a solution? for _ValidationRules2.default[name] is not a function???

**Comment by Standin-Alone** [comment]
any updates or solution?   _ValidationRules2.default[name] is not a function

**Comment by NewOldMax** [comment]
@Standin-Alone please make reproducible case [here](https://codesandbox.io/s/new)

**Comment by menashkes** [comment]
I had the same problem. I looked at the code of the library and realized that the code will go to if the validator is not "required". I wrote "Required" so I changed it to lower case and it solved it..

I guess it was expecting a custom validator..

Hope that helps.
