### ISSUE TITLE
Can't resolve 'react-autosuggest'

### ISSUE THREAD

**Issue by rszemplinski** [NewOldMax/react-material-ui-form-validator#46]
Hi,

I just stumbled across this package and wanted to try it out but when I install it I get this error message:

```
./~/react-material-ui-form-validator/lib/AutoCompleteValidator.js
Module not found: Can't resolve 'react-autosuggest' in '/Users/{account}/Documents/lodestar-client/node_modules/react-material-ui-form-validator/lib'
```

I installed the core package and am using Material UI 1.x but I am not using React 16. Could that be the problem?

Thanks!

**Comment by NewOldMax** [comment]
dup #35
