### ISSUE TITLE
Debounce property?

### ISSUE THREAD

**Issue by rszemplinski** [NewOldMax/react-material-ui-form-validator#47]
Hi,

I was wondering if you had some built-in debounce feature or were planning on adding it in anytime soon?

**Comment by NewOldMax** [comment]
Hi,

you mean something like this https://www.npmjs.com/package/react-debounce-input ?

**Comment by rszemplinski** [comment]
I was thinking that your `ValidatorForm` would have a property that would be `debounceTime` or something if `instantValidate` is on.

**Comment by NewOldMax** [comment]
I'm not planing to implement this feature, but feel free to make a PR.
Reopen this if needed

**Comment by NewOldMax** [comment]
will implement this soon

**Comment by NewOldMax** [comment]
Added in 1.0.7
