### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by nanocreaator** [NewOldMax/react-material-ui-form-validator#48]
Hi!
A question: any chance to use with react-number-format?
(https://github.com/s-yadav/react-number-format)

Thanks

**Comment by NewOldMax** [comment]
Hi,
dunno try to use `customInput` prop. Or you can implement your own validation component ([example](https://github.com/NewOldMax/react-material-ui-form-validator/blob/master/src/TextValidator.jsx)) and extend it as you want

**Comment by nanocreaator** [comment]
Hi,
Thanks. I tried to extends as you suggested and I am having the error below.
<img width="1028" alt="captura de tela 2018-01-14 as 14 13 14" src="https://user-images.githubusercontent.com/3308721/34916255-92f79234-f935-11e7-93d7-638b86816c51.png">

Maybe I miss something... I am using material V1.
Thanks
