### ISSUE TITLE
Unmet peer dependency error

### ISSUE THREAD

**Issue by keycad** [NewOldMax/react-material-ui-form-validator#49]
With `react-material-ui-form-validator@2.0.0-beta.2` the package shows UNMET PEER DEPENDENCY error.

![image](https://user-images.githubusercontent.com/20127623/34946319-b6929640-fa06-11e7-8cf4-6a7dfa89c8c4.png)

This is caused because the library has a required dependency on `material-ui@next`, but when you install `material-ui@next` it is `actually material-ui@1.0.0-beta.26`. 
See package.json: https://github.com/NewOldMax/react-material-ui-form-validator/blob/e0afddd2686fed0dd3964b26e16d5c1a30da534e/package.json#L27

I have tried manually updating your package.json from my node-modules to the exact version and the error dissapears.

**Comment by NewOldMax** [comment]
Hi,
can you show your `package.json`?

**Comment by keycad** [comment]
Sure, this is it:

```
{
  "name": "lib-xxx",
  "version": "0.1.0",
  "description": "Lib XXX",
  "main": "src/index.tsx",
  "types": "src/index.d.ts",
  "dependencies": {
    "material-ui": "1.0.0-beta.26",
    "prop-types": "15.6.0",
    "react": "16.0.0",
    "react-autosuggest": "9.3.2",
    "react-dom": "16.0.0",
    "react-material-ui-form-validator": "2.0.0-beta.2",
    "react-redux": "5.0.6",
    "react-router-dom": "4.2.2",
    "redux": "3.7.2"
  },
  "devDependencies": {
    "@types/node": "8.0.51",
    "@types/react": "16.0.9",
    "@types/react-dom": "16.0.0",
    "css-loader": "0.28.7",
    "file-loader": "1.1.6",
    "node-sass": "4.7.2",
    "sass-loader": "6.0.6",
    "style-loader": "0.18.2",
    "ts-loader": "2.3.7",
    "typescript": "2.5.3",
    "url-loader": "0.6.2",
    "webpack": "3.8.1",
    "webpack-dev-server": "2.9.2"
  }
}
```

**Comment by NewOldMax** [comment]
And if you change
````
"material-ui": "1.0.0-beta.26",
````
to
````
"material-ui": "next",
````
?

**Comment by keycad** [comment]
Hi, yes, that also removes the error. The thing is we work with fixed versions in our team, to prevent one person having a different module version than other

**Comment by NewOldMax** [comment]
Yeah, but this library has v1 beta support, that's why I'm waiting for stable release and keeping `next` as dependency. You can fork it and use your version as well

**Comment by keycad** [comment]
ok, thanks!
