### ISSUE TITLE
Regexp validator that include colon in the regex will fail

### ISSUE THREAD

**Issue by ValYouW** [NewOldMax/react-material-ui-form-validator#5]
Hi,

I am trying to use `matchRegexp` validator as follow: `validators={['matchRegexp:^(https?|ftp):\/\/[^\s\/$.?#]+\\.[^\s]*$']}` - since the regexp value contains `:` the library fails to extract the regexp value correctly...
thx

**Comment by NewOldMax** [comment]
Hi @ValYouW , thanks for reporting the issue, i'll check this

**Comment by FintanK** [comment]
Didn't fix this?

**Comment by NewOldMax** [comment]
@FintanK 
you can see an accepted [PR](https://github.com/NewOldMax/react-material-ui-form-validator/commit/ae196c95b75c58c5548ab60610d5805baecaf0bd) for this
