### ISSUE TITLE
How to use regex modifiers in matchRegexp?

### ISSUE THREAD

**Issue by Cristy94** [NewOldMax/react-material-ui-form-validator#50]
I want to match something case insensitive, for exmaple:

`validators={['matchRegexp:/(https?:\/\/.*\.(?:png|jpg))/i']}`

But this doesn't work as the `matchRegexp` expected value is a string not a RegExp.

**Comment by NewOldMax** [comment]
Hi
It's not possible with current implementation, but you always can create a custom validation rule

**Comment by MarekLani** [comment]
is it still unsupported?
