### ISSUE TITLE
v1 validation support

### ISSUE THREAD

**Issue by mhafer** [NewOldMax/react-material-ui-form-validator#51]
Hi, I'm using...

  react-form-validator-core: ^0.4.1
  react-material-ui-form-validator: ^2.0.0-beta.3
  material-ui: 1.0.0-beta.30

Does TextValidator support all these:
matchRegexp
isEmpty
trim
isNumber
isFloat
isPositive
minNumber
maxNumber
minStringLength
maxStringLength
isString

as well as custom validations? I used a few of these (minStringLength, matchRegexp, custom: isPasswordMatch) with an older version of material-ui. But now I'm having troubles getting them to work with the newest version.

IsEmail and Required are the only ones that seem to work for me at the moment.

Thank you in advance!

**Comment by NewOldMax** [comment]
Hi,
2-beta release doesn't support `react-form-validator-core` for now, so you should use internal components
````javascript
import { ValidatorForm } from 'react-material-ui-form-validator';
````
and it doesn't support `minStringLength`, `maxStringLength` and `isString` 😢 
Later I will upgrade it

**Comment by NewOldMax** [comment]
Fixed in beta4
