### ISSUE TITLE
TextValidator InputAdornment        

### ISSUE THREAD

**Issue by mhafer** [NewOldMax/react-material-ui-form-validator#53]
Hello,

I'm using material-ui: 1.0.0-beta.31 with TypeScript and would like to use the InputAdornment feature. Am I able to use that with your TextValidator? I was struggling to get it to work.

This is what I was doing before (without validation):
`<FormControl>
                    <InputLabel htmlFor="password">Password</InputLabel>
                    <Input
                      id="password"
                      type={this.showPassword ? "text" : "password"}
                      value={this.password}
                      onChange={(e: any) => this.handleInputChange(e.target)}
                      endAdornment={
                        <InputAdornment position="end">
                          <IconButton
                            onClick={this.togglePassword}
                            onMouseDown={() => (e) => event.preventDefault()}>
                            {this.showPassword ? <VisibilityOff /> : <Visibility />}
                          </IconButton>
                        </InputAdornment>}
                      margin="dense"
                      fullWidth />
                  </FormControl>`

Then I switched to using TextValidator:

`                  <TextValidator
                    label="Enter Password"
                    name="password"
                    id="password"
                    type="password"
                    validators={['required', 'matchRegexp:[A-Z]+', 'matchRegexp:[a-z]+','isPasswordLength']}
                    errorMessages={['required field', 'must contain at least 1 uppercase', 'must contain at least 1 lower case','must be at least 8 characters']}
                    value={this.reg.password}
                    onChange={(e: any) => this.handleInputChange(e.target)} />`

I like the TextValidator I just want a way to use the InputAdornment feature on it :)

Hope that makes sense, thanks!

**Comment by NewOldMax** [comment]
Hi,
try to use something like this
````javascript
<TextValidator
    ...
    InputProps={{
              endAdornment: (
                <InputAdornment position="end">
                    ...
                </InputAdornment>
              )
        }}
/>
````

**Comment by mhafer** [comment]
Thank you it worked! 🎉
