### ISSUE TITLE
How can know if all the form fields are validated or a specific is valid?

### ISSUE THREAD

**Issue by pavanshinde47** [NewOldMax/react-material-ui-form-validator#54]
Hi,

I am working on the a form. The submit button will be disabled if the form is not valid. I am not able to find a way to do this.  I see there are methods available for this but not sure how to use them here. Can anyone help please.

**Comment by NewOldMax** [comment]
Please check [demo](https://newoldmax.github.io/react-material-ui-form-validator/) **Step-by-step** example, there is disabling submit button when validation fails
