### ISSUE TITLE
json-schema as standard

### ISSUE THREAD

**Issue by zsolt-dev** [NewOldMax/react-material-ui-form-validator#55]
This package looks great. 

Is there a reason to not use a standard json schema? I have a json schema on the backend to validate the form, so It would be nice to use the same schema on the client too.

Is there a plan or a way to use json schema instead of custom validation rules?

If this would be implemented, this package would skyrocket in popularity...

thank you

**Comment by NewOldMax** [comment]
At start of this project I've found that custom validation rules is more convenient for me, so I develop it in that way, and it looks more simpler for user.

So no plans for json shema
