### ISSUE TITLE
Remove dependency on material-ui@next

### ISSUE THREAD

**Issue by triqi** [NewOldMax/react-material-ui-form-validator#56]
`react-material-ui-form-validator` has a dependency on `material-ui` by a tag name `@next`. This will cause the dependency validation to fail.

> npm ERR! peer dep missing: material-ui@next, required by react-material-ui-form-validator@2.0.0-beta.4

**Steps to reproduce**

1. `npm install material-ui@next` which will result in e.g. `material-ui@1.0.0-beta.33` saved to `package.json`
2. `npm install react-material-ui-form-validator@next`
3. `npm ls -prod -json -depth=1`

**Comment by NewOldMax** [comment]
It's just a peer dependency which shows that you need something to get it work, but since material-ui v1 isn't released as stable I won't change this behavior. It's beta support anyway
