### ISSUE TITLE
displayEmpty not being passed down to the select component

### ISSUE THREAD

**Issue by felipenmoura** [NewOldMax/react-material-ui-form-validator#57]
Not sure if this is a problem with the select validator itself, or if it's me, who is doing something wrong here.

When I use `displayEmpty`, it triggers an error:
`React does not recognize the "displayEmpty" prop on a DOM element`

The code is plain simple like:

```
<SelectValidator
  displayEmpty
  .... >
...
</SelectValidator>
```

If that works for you, then I will take a deeper look in some dependencies of mine and in some abstractions I'm trying to create with it.

  > `displayEmpty` comes from the `Select` component described at the [Select docs](https://material-ui-next.com/api/select/)

**Comment by NewOldMax** [comment]
Hi,
you can see that [SelectValidator](https://github.com/NewOldMax/react-material-ui-form-validator/blob/v1/src/SelectValidator.jsx) uses `select` mode for `TextField`, so, as described in [docs](https://material-ui-next.com/demos/text-fields/#textfield) (open the source of first example), you should pass all specific select props as `SelectProps`.
So it will be something like this
````javascript
<SelectValidator
    SelectProps={{
        displayEmpty: true
    }}
>
````

**Comment by felipenmoura** [comment]
Nice, makes sense. I thought it was using a `SelectField`.

Thanks.
