### ISSUE TITLE
How to implement `matchRegexp` for IP address validation?

### ISSUE THREAD

**Issue by ras24** [NewOldMax/react-material-ui-form-validator#58]
I need to validate an IP address using `matchRegexp`.
>     
        <TextValidator 
             name='host'
             label='Host'
             value={this.state.fields.host}
             onChange={this.onInputChange}
             validators={['matchRegexp:^(?=\d+\.\d+\.\d+\.\d+$)(?:(?:25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9][0-9]|[0-9])\.?){4}$']}
             errorMessages={['ip address is not valid']}
        />
I used regex from this [link](https://stackoverflow.com/a/26671130/9289169)

If we run the code snippet from link above, we can see the list of valid and invalid ip address like image below:
![screen shot 2018-03-24 at 1 58 39 am](https://user-images.githubusercontent.com/13892486/37845887-f085004c-2f06-11e8-944f-8516de605df4.png)

I tried to type a valid ip address but the `errorMessages` still shown.
![screen shot 2018-03-24 at 1 52 46 am](https://user-images.githubusercontent.com/13892486/37845674-2f813136-2f06-11e8-83f9-afe85f560769.png)

How to make it works?

**Comment by NewOldMax** [comment]
Hi,
Can you create a snippet from this template?
https://codesandbox.io/s/p52x38v22m

**Comment by ras24** [comment]
Thank you for your response,
This is the [snippet](https://codesandbox.io/s/y3z8plzlnx)

**Comment by NewOldMax** [comment]
Regexp value is created from string, so you need to escape backslashes with another backslashe.
So, your regexp will be
````
validators={['matchRegexp:^(?=\\d+\\.\\d+\\.\\d+\\.\\d+$)(?:(?:25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9][0-9]|[0-9])\\.?){4}$']}
````

**Comment by ras24** [comment]
Thank you very much @NewOldMax
