### ISSUE TITLE
Validator Form is not reset.

### ISSUE THREAD

**Issue by vineet-agrawal96** [NewOldMax/react-material-ui-form-validator#60]
Hi...
To reset form I'm using the following code but form not reset and giving the error:-
  this.refs.form.resetValidations();

But following error is coming 
Uncaught TypeError: _this.refs.form.resetValidations is not a function. 

Please help.

Thanks
Vineet Agrawal

**Comment by NewOldMax** [comment]
Hi,
can you create a snippet [here](https://codesandbox.io/s/p52x38v22m) to reproduce your issue?

**Comment by vineet-agrawal96** [comment]
Hi,

Thanks for the quick reply. The issue is resolved, which is coming because of the older version(0.5.0). Now, I've updated it.

Would you tell me please, there is any function which tells us the whole form is valid or not?

**Comment by NewOldMax** [comment]
You can set `validatorListener` on inputs, if some of them returns `false`, your form validation is invalid

**Comment by vineet-agrawal96** [comment]
I applied validatorListener but it's working when the form is submitted. I want to check, the form is valid or not before click on submit button. My purpose is if the form is valid then enable submit button otherwise it will be disabled.

**Comment by NewOldMax** [comment]
You can see it [here](https://newoldmax.github.io/react-material-ui-form-validator/), **Step-by-step** example

**Comment by vineet-agrawal96** [comment]
The step-by-step example is working only for one input field.  if the form has multiple input field then validatorListener called for each input. In that case, disabled button condition failed.

is there any way to check entire form is valid or not before submission of form?

**Comment by NewOldMax** [comment]
Currently not. You can run validation manually, something like this
````javascript
    <ValidatorForm ref={r => (this.form = r)} >
        <TextValidator ref={r => (this.input = r)} />
    </ValidatorForm>

// run for whole form
runFormvalidation = () => {
    this.form.walk(this.form.childs);
}

// run for some input
runInputValidation = () => {
    this.input.validate(inputValue)
}
````

**Comment by shyamambady** [comment]
I am using the 1.1.0 version 

I gets error when i using this.refs.form.resetValidations();

Any other approach to reset the error message

Please help.

**Comment by shyamambady** [comment]
I have shared code snippet here https://codesandbox.io/s/3ywkn2xrz6 .  In the package.json i have  changed the version of material ui and form validator as  that i am using now .

"dependencies": {
    "material-ui": "0.19.4",
    "react": "16.2.0",
    "react-autosuggest": "9.3.2",
    "react-dom": "16.1.1",
    "react-material-ui-form-validator": "1.1.0"
  }


please help me.

**Comment by NewOldMax** [comment]
@shyamambady 
you have an error here
````javascript
this.refS.form.resetValidations();
````
it should be 
````javascript
this.refs.form.resetValidations(); // S -> s
````

**Comment by shyamambady** [comment]
Thanks for your reply.

**Comment by NewOldMax** [comment]
I guess that issue is fixed so I close it
