### ISSUE TITLE
how to validate form in beta version of material ui

### ISSUE THREAD

**Issue by anilljoshi** [NewOldMax/react-material-ui-form-validator#61]
How can i use from validation for beta version because current version is showing error  do i need to install next version ?
**npm i react-material-ui-form-validator@next**

**Comment by NewOldMax** [comment]
You can do this in the same way as stable version

**Comment by anilljoshi** [comment]
but its showing this error
ERROR in ./node_modules/react-material-ui-form-validator/lib/AutoCompleteValidator.js
Module not found: Error: Can't resolve 'material-ui/AutoComplete' in 'D:\www\master2018D\node_modules\react-material-ui-form-validator\lib'

and i have impor your component like this
import { TextValidator, ValidatorForm } from 'react-material-ui-form-validator';

**Comment by NewOldMax** [comment]
Please, check [versions](https://github.com/NewOldMax/react-material-ui-form-validator/releases) section

> => 2.x - supports material-ui >= 1.x (experimental support, you can install it by npm i react-material-ui-form-validator@next)

**Comment by anilljoshi** [comment]
thanks, I have installed "react-material-ui-form-validator": "^2.0.0-beta.4" and its working as expecting
