### ISSUE TITLE
<SelectValidator> ¿?

### ISSUE THREAD

**Issue by Villanuevand** [NewOldMax/react-material-ui-form-validator#63]
Hey guys. 

I having a bad time with `SelectValidator` implementatión   ... 
Can anybody help me with this error ? 

`SelectInput.js:289 Uncaught Error: Material-UI: the `value` property is required when using the `Select` component with `native=false` (default).`

Version: `"material-ui": "^1.0.0-beta.42",`

<img width="349" alt="captura de pantalla 2018-04-23 a la s 18 09 26" src="https://user-images.githubusercontent.com/1209238/39153497-b03fe3ca-4721-11e8-9ad4-4cee74222d15.png">

¡Thank you guys!

**Comment by NewOldMax** [comment]
Hi,
can you reproduce your issue [here](https://codesandbox.io/s/p52x38v22m)?

**Comment by Villanuevand** [comment]
Done! => https://codesandbox.io/s/yko638j311 @NewOldMax

**Comment by NewOldMax** [comment]
https://codesandbox.io/s/zrkxnm3lol
in this library `SelectValidator` uses `TextField` component, so you should pass select-specific props in `SelectProps`:
````javascript
<SelectValidator
          name="bank"
          id="banks"
          onChange={this.changeHandler}
          value={this.state.bank}
          SelectProps={{
            native: true
          }}
>
````
Also to make validation work you should pass `value` prop

**Comment by Villanuevand** [comment]
Thanks @NewOldMax ....
