### ISSUE TITLE
Material-ui-pickers with ValidatorForm

### ISSUE THREAD

**Issue by mohanajuhi** [NewOldMax/react-material-ui-form-validator#66]
Is it possible to  implement validations for  material-ui-pickers in ValidatorForm ?
For Example ,   is it possible to throw "please enter valid date" for the following element if i dont enter any date

I am using  **material-ui-pickers**

 <DatePicker
                    format="DD/MM/YYYY"
                    leftArrowIcon={<KeyboardArrowLeft />}
                    rightArrowIcon={<KeyboardArrowRight />}
                    keyboardIcon
                    minDate={endDate}
                    disabled={this.state.onwardDateSet}
                    errorText={n.dateVar ? {} : 'please enter date'}
                    placeholder="dd/mm/yyyy"
                    mask={value => (value ? [/\d/, /\d/, '/', /\d/, /\d/, '/', /\d/, /\d/, /\d/, /\d/] : [])}
                    value={n.dateVar}
                    onChange={(e) => this.handleChangeTableDate(e, n.idRR, 'return')}
                    disableOpenOnEnter
                    animateYearScrolling={false}
                  />

**Comment by NewOldMax** [comment]
Hi,
you can find an example [here](https://codesandbox.io/s/k2yjl59n3)

**Comment by mohanajuhi** [comment]
if minDate  attribute is a date in the future, and if I click on the picker, by default it shows today's date. If I select "ok" , and submit the form, it doesnt throw any error

**Comment by NewOldMax** [comment]
It's your app logic issue, not validation library. Just create correct initial state and validation rules
