### ISSUE TITLE
TextValidator with Icon

### ISSUE THREAD

**Issue by lucasharada** [NewOldMax/react-material-ui-form-validator#67]
Is there a way to use this TextValidator with Icon, as shown in [Material-UI](https://material-ui-next.com/demos/text-fields/#with-icon)? I tried passing `startAdornment` prop, but had no success.

**Comment by NewOldMax** [comment]
Hi,
can you write an example with your issue [here](https://codesandbox.io/s/p52x38v22m)?

**Comment by lucasharada** [comment]
My mistake! I was trying to use `startAdornment` prop like in Input, instead of using `InputProps`! Thanks!
