### ISSUE TITLE
The latest 2.0.0-beta.9 has the following warnings. 

### ISSUE THREAD

**Issue by skykoradji** [NewOldMax/react-material-ui-form-validator#69]
main.js:5277 Warning: Unsafe legacy lifecycles will not be called for components using new component APIs.

TextValidator uses getDerivedStateFromProps() but also contains the following legacy lifecycles:
  componentWillReceiveProps

The above lifecycles should be removed. Learn more about this warning here:
https://fb.me/react-async-component-lifecycle-hooks

**Comment by NewOldMax** [comment]
This library doesn't use `componentWillReceiveProps` method, issues is related to [material-ui input](https://github.com/mui-org/material-ui/blob/303199d39b42a321d28347d8440d69166f872f27/packages/material-ui/src/Input/Input.js)
