### ISSUE TITLE
Using TextValidator with MaskedInput

### ISSUE THREAD

**Issue by lucasharada** [NewOldMax/react-material-ui-form-validator#70]
How can I apply TextValidator with MaskedInput (from [Text-Mask](https://github.com/text-mask/text-mask))?

I tried passing the Masked Component through `InputProps`...:

**TextValidator:**
```
<TextValidator
    label='ID'
    name='id'
    value={this.state.id}
    InputProps={{
        inputComponent: IDMaskedInput,
        inputProps: {
            onIDChange: this.handleIDChange
        }
    }}
    margin='normal'
    autoComplete='email'
    validators={['isValidID']}
    errorMessages={['Invalid ID]}
/>
```

**IDMaskedInput:**
```
<MaskedInput
    mask={mask}
    placeholderChar={'\u2000'}
    placeholder='12.123.123/1234-12'
    value={this.props.value}
    onChange={(event) => this.props.onCNPJChange(event)}
    showMask={false}
    keepCharPositions={false}
/>
```

But the UI for the Input got all messed up:

<img width="134" alt="captura de tela 2018-05-15 as 13 55 59" src="https://user-images.githubusercontent.com/18669473/40071643-c1dfcd98-5847-11e8-9ccf-af093e7a9205.png">

Initially, the Input covers the Label like the image above. When the Input box in focused, the Label goes up and works properly. Is there a way to use both components together?

**Comment by NewOldMax** [comment]
Hi,
can you provide an example from [this snippet](https://codesandbox.io/s/yl8p9jvq9)?

**Comment by NewOldMax** [comment]
So, it's not a problem with this library, You can check [example](https://material-ui-next.com/demos/text-fields/#formatted-inputs) from material-v1 docs. Your problem is `MaskedInput` component. You don't pass props from material-ui to input. Check it [here](https://codesandbox.io/s/6w8py492r)

**Comment by lucasharada** [comment]
Thanks for your help! 

Just let me add one thing: on your last CodeSandbox, you're using `<TextField />` instead of `<TextValidator />`. Just swap and we have the form working properly with the validation!

**Comment by NewOldMax** [comment]
Yes, I've just tested with native `TextField`
