### ISSUE TITLE
Can you get results of previous validation?

### ISSUE THREAD

**Issue by maxchernin** [NewOldMax/react-material-ui-form-validator#73]
Im running 3 validations on a field:

one returns true,
second returns false
the third returns true.
the form is colored nicely, but
in each validation i also set my state.isValid prop to the return statement as well.
my question is, is there a way for me to check all validations running on the array and set my state accordingly?
e.g.

if(ValidatorForm.validation1 && ValidatorForm.validation2 && ValidatorForm.validation3){
this.setState({isValid: true});
} 
or should i create a isValid prop for each validation in my object?

**Comment by NewOldMax** [comment]
But you already can get validation result of input, see [validatorListener](https://github.com/NewOldMax/react-form-validator-core/blob/master/src/ValidatorComponent.jsx#L105)
alternatively you can get an array of keys of invalid validations 
````javascript

listener = (isValid) => {
    const invalidValidations = this.input.invalid;
}

<TextValidator
    ref={r = (this.input = r)}
    validatorListener={listener}
/>

````

**Comment by maxchernin** [comment]
thanks. didn't notice this , is it feature documented?

**Comment by NewOldMax** [comment]
`validatorListener` is documented, and `invalid` array you can check from sources
