### ISSUE TITLE
Backward compatability

### ISSUE THREAD

**Issue by Sashikanth-K** [NewOldMax/react-material-ui-form-validator#74]
As mentioned in the ReadMe.md

> 0.x, 1.x - supports material-ui <= 0.x
> up to 2.0.0-beta.9 - supports material-ui >= 1.x (you can install it by npm i react-material-ui-form-validator@2.0.0-beta.9)
> from 2.0.0-beta.10 - supports @material-ui/core (you can install it by npm i react-material-ui-form-validator@next)
> 

but version 2.0.0-beta.9   is dependent on  **material/core**

**Comment by NewOldMax** [comment]
Hi,

where you see this dependency on 2.0.0-beta.9?

**Comment by NewOldMax** [comment]
stable 2.0.0 is released so this can be closed
