### ISSUE TITLE
Scroll and focus on the error filed after submit button click 

### ISSUE THREAD

**Issue by jaisonjjames** [NewOldMax/react-material-ui-form-validator#75]
I would like to know any method/feature available like a scroll and focus on the first element with validation error after click on the submit button or how can I archive it?

**Comment by NewOldMax** [comment]
Hi,

you can do it in the following way:
````javascript
const myFunc = (isValid, inputName) => {
   if (!isValid) {
      // your some scroll/focus logic, you can use inputName or some ref
   }
}

<TextValidator
    ...
    name="email"
    validatorListener={(isValid) => myFync(isValid, 'email')}
/>
```

**Comment by zhangyuting1** [comment]
Could anyone help show an example how to implement the  scroll/focus logic with inputName or some ref, in react. 
Really appreciated!

**Comment by zhangyuting1** [comment]
> @mrazicz @NewOldMax @ValYouW
> Could anyone help show an example how to implement the scroll/focus logic with inputName or some ref, in react.
> Really appreciated!
> I tried to add refs for the. TextValidator, but it complains the focus is not a function... anyone met this error before?
> 
> my sample code:
> 
> 1. define the ref:
>    this.title = React.createRef();
> 2. add to TextValidator:
>    <TextValidator
>    ......
>    ref={this.title}
>    validatorListener={(isValid) => this.myFunc(isValid)}
>    />
> 3. define myFunc
>    myFunc = (isValid) => {
>    if (!isValid) {
>    if (this.title.current!==null){
>    this.title.current.focus();
>    }
>    }
>    }
> 
> Then:
> Uncaught TypeError: _this.title.current.focus is not a function
> at EditorDialog._this.myFunc (EditorDialog.jsx:186)
> at Object.validatorListener (EditorDialog.jsx:662)
> 
> And in fact, no focus function indeed. But I do not think should add foucs function there, it should have by default,right?
> ![image](https://user-images.githubusercontent.com/7311213/88475096-7af5e700-cf5f-11ea-9979-2be949ca8978.png)

I can only make it work in this way:

ReactDOM.findDOMNode(this.refs[inputName]).scrollIntoView({ behavior: 'smooth' });

**Comment by ValYouW** [comment]
I moved all my forms to [react-jsonschema-form](https://github.com/rjsf-team/react-jsonschema-form) so no longer using this....
