### ISSUE TITLE
SelectValidator using textfield?

### ISSUE THREAD

**Issue by fadeenk** [NewOldMax/react-material-ui-form-validator#79]
Why is the SelectValidator using TextField component instead of a select?

https://github.com/NewOldMax/react-material-ui-form-validator/blob/43b5cb68366e595f1fa8abff8d03b5d45acdf3d4/src/SelectValidator.jsx#L22

**Comment by fadeenk** [comment]
The main reason I am asking because someone might be interested in utilizing some of the added functionality such as support for multiple fields. It doesn't really affect me, I was just curious.

**Comment by NewOldMax** [comment]
Anyway you always can implement your own select validator by extending ValidatorComponent, it's simple

**Comment by Alexpress94** [comment]
@fadeenk I had the problem you mentioned (I wanted a select with multiple field selection) and after starting extending the ValidatorComponent I realized I could provide the TextField with the select props:
``
<SelectValidator
  SelectProps={{ multiple: true }}
  { ...this.props }
>
   { this.props.children }
</SelectValidator>
``
:)

**Comment by agjs** [comment]
@Alexpress94 Cheers mate, you save me some time!

**Comment by ninjakatie** [comment]
> @fadeenk I had the problem you mentioned (I wanted a select with multiple field selection) and after starting extending the ValidatorComponent I realized I could provide the TextField with the select props:
> 
> ```
> <SelectValidator
>   SelectProps={{ multiple: true }}
>   { ...this.props }
> >
>    { this.props.children }
> </SelectValidator>
> ```

Been breaking my head over this, thank you for posting!!
