### ISSUE TITLE
Form submission: Cannot read property 'preventDefault' of undefined

### ISSUE THREAD

**Issue by darrensw777** [NewOldMax/react-material-ui-form-validator#8]
I have the following code:

```
export default class RegisterForm extends Component {

  constructor(props) {
    super(props);

    this.state = {

    };
    this.handleSubmit = this.handleSubmit.bind(this);
  }
 ....

handleSubmit(e) {
    e.preventDefault();
    var payload = this.state;
....

render() {
    return (
      <ValidatorForm ref="form" onSubmit={this.handleSubmit}>
          <TextValidator
              floatingLabelText="Name"
              onChange={this.handleChange}
....

          <RaisedButton label="Register" type="submit" />
      </ValidatorForm>
      );
  }
}
```

When submitting I get the following error:

> Uncaught TypeError: Cannot read property 'preventDefault' of undefined

This should work, shouldn't it? Is there anything under the hood I've missed?

Many thanks, love the plug-in by the way, will do a PR when I have time and add some more validation types if any good for you

**Comment by NewOldMax** [comment]
Hi
As you can [see](https://github.com/NewOldMax/react-material-ui-form-validator/blob/master/src/ValidatorForm.jsx#L63), `event` already "prevented". If you want to use `event` for some purposes, I can add it to `submit` callback

**Comment by darrensw777** [comment]
Hi

Arrghh - I must have skipped over that - thanks for the swift reply, appreciated.

Last question, I also get the following warning:

> Warning: TextField is changing an uncontrolled input of type text to be controlled.

Have you seen that? Not on submission, on change in a `<TextValidator />` field

**Comment by NewOldMax** [comment]
It happens when your value was `null` or `undefined` before changing.
````javascript
state = {
    user: {}
};

<TextValidator
    value={user.email}    <------ first time user.email = undefined, so react thinks that is uncontrolled input
/>
````
And you can do something like this to avoid error

````javascript
state = {
    user: {
        email: ''  <---- empty string by default
    }
};

<TextValidator
    value={user.email}    <------ works without warning
/>
````
Or something like `value={user.email || ''}`

**Comment by darrensw777** [comment]
Can't thank you enough, only just started on React...it's good so far but sometimes a bit strange in it's warnings... thanks again, much appreciated
