### ISSUE TITLE
Hi :) I'm trying to use your project for material-ui-next

### ISSUE THREAD

**Issue by shmeliavCoder** [NewOldMax/react-material-ui-form-validator#81]
literaly just used:

```
create-react-app my-app
npm install material-ui
npm install react-material-ui-form-validator

```
and added the line 
`import { TextValidator} from 'react-material-ui-form-validator';`

to the file app.js
the error that occurs on load is as follows : 
Failed to compile
./node_modules/react-material-ui-form-validator/lib/SelectValidator.js
Module not found: Can't resolve '@material-ui/core/TextField' in 'C:\...\my-app\node_modules\react-material-ui-form-validator\lib'

obviously the path of material-ui isnt the path this project is expecting, but your documentation says that the last version of this project supports material-ui v1 and above so I'm wondering how am I supposed to install and use it? is there a way to change the path of material-ui/TextField to be @material-ui/Core/TextField like you are expecting? (maybe also add that library as a dependency as well)

**Comment by NewOldMax** [comment]
Hi,
as you can see in [docs](https://material-ui.com/getting-started/installation/), you should install `@material-ui/core` to use material-ui v1 (it was breaking change from material-ui team)
