### ISSUE TITLE
Way to add custom validation on submit

### ISSUE THREAD

**Issue by vibolvireak** [NewOldMax/react-material-ui-form-validator#85]
Example i have one login form contain email and password fields

Validation should work as expect when key press if email and password is not empty or email is in valid format. After everything ok user will press submit button and a server will send error ex email or password not correct.

**Question**

How can we have a custom validation running when form already submit and recieve error result?

**Comment by NewOldMax** [comment]
Hi
try to run validation [manually](https://github.com/NewOldMax/react-form-validator-core/issues/12)

**Comment by vibolvireak** [comment]
Is there any example available on how to validate from an api server. ? trying almost 2hour and still no luck..

**Comment by NewOldMax** [comment]
Now you can use promises in your custom validations as well
Check the `0.6.1` version
