### ISSUE TITLE
problem with resetValidations

### ISSUE THREAD

**Issue by wojciktomasz** [NewOldMax/react-material-ui-form-validator#86]
I have a component that I use for editing form data and as well as adding data. 

On change of path I want to clear out the form, and prevent it from validating, so the field is not marked red after rerender. Like this: 

```
componentWillReceiveProps(nextProps) {
    if (nextProps.location.pathname !== this.props.location.pathname) {
      this.setState({
        name: ''
      }, () => this.refs.form.resetValidations())
    }
  }
```
I have added a proper ref for the form:
```
<ValidatorForm
        onSubmit={this.handleUpdateAndBackToList}
        onError={errors => console.warn(errors)}
        ref='form'
      >
```
And the setup for the field as follows:
```
<TextValidator
              style={styles}
              name="name"
              validators={['minStringLength: 1']}
              errorMessages={['To pole jest wymagane']}
              label="Nazwa źródła"
              value={this.state.name}
              onChange={this.handleSourceNameChange('name')}
            />
```

Yet, I cannot prevent the form from validating on change of path, and the field is marked red. Like the resetValidation() is not working properly.

Any solutions to this?

**Comment by NewOldMax** [comment]
Hi
can you reproduce your issue [here](https://codesandbox.io/s/p52x38v22m)?

**Comment by wojciktomasz** [comment]
No problem, it's right here: https://codesandbox.io/s/2vnpqlqn20

I want to do something a little more complex, but for the issue here what I want to do is basically just have some text in the name field, then press the reset button to set the value to an empty string and not have the field validated - that's why I'm using the resetValidation function as a callback to the setState. Without much success though.

**Comment by NewOldMax** [comment]
Currently validation runs every time when `value` of input is changed.
As a workaround you can disable `instantValidate` for whole form and it will validate only when you press submit button

**Comment by wojciktomasz** [comment]
Well, that really doesn't solve my problem, as I would still like it to instantValidate :)

There is no other way to not validate the field on rerender? What I really want to do is I would like to make it work just like you first render the component.

**Comment by NewOldMax** [comment]
It's not a `rerender`. Validating function runs every time when value is changed (and you changed it). You still can disable `instantValidate` and run `validate` manually, after `handleChange` function for example

**Comment by wojciktomasz** [comment]
Ok, I got you. Thanks for your help!
