### ISSUE TITLE
"react-material-ui-form-validator" version for "material-ui" version "^1.0.0-beta.37"

### ISSUE THREAD

**Issue by MehdiJarraya** [NewOldMax/react-material-ui-form-validator#87]
Hi guys, 
I'can't find the correct version of "react-material-ui-form-validator" for "material-ui" version ^1.0.0-beta.37.
I already tried react-material-ui-form-validator version 1.1.5 and 2.0.1 but they didn't work.

**Comment by NewOldMax** [comment]
Hi
try to use `2.0.0-beta.10`

**Comment by MehdiJarraya** [comment]
Thank you @NewOldMax , it works perfectly now.
