### ISSUE TITLE
warning when using material-ui 3.0

### ISSUE THREAD

**Issue by VDGSecurity** [NewOldMax/react-material-ui-form-validator#88]
I am having material-ui/core/3.0.1 installed, and receiving the following warning. Everything works ok, but don't like warnings ;-)

`npm WARN react-material-ui-form-validator@2.0.1 requires a peer of @material-ui/core@^1.0.0 but none is installed. You must install peer dependencies yourself.`

**Comment by NewOldMax** [comment]
fixed in `2.0.2`
