### ISSUE TITLE
why selected option is hidden in react ?

### ISSUE THREAD

**Issue by naveennsit** [NewOldMax/react-material-ui-form-validator#89]
hi
I made a simple demo of form using react material, in which I have only one `select` field .I used this link to make select option
https://material-ui.com/demos/selects/
using `api` I am able to show label at top (using this `shrink={true}`)and show disabled value using this `displayEmpty`.
so my form look like this without any validation
https://codesandbox.io/s/8x4wnjnrz8

Now i try to validate my form using this plugin
https://www.npmjs.com/package/react-material-ui-form-validator
but my default option is hidden and select box label is also look awkward and with become small 

here is my code
https://codesandbox.io/s/8x4wnjnrz8 

    import ReactDOM from "react-dom";
    import React from "react";
    import PropTypes from "prop-types";
    import { withStyles } from "@material-ui/core/styles";
    import Input from "@material-ui/core/Input";
    import InputLabel from "@material-ui/core/InputLabel";
    import MenuItem from "@material-ui/core/MenuItem";
    import FormHelperText from "@material-ui/core/FormHelperText";
    import { FormControl, Button } from "@material-ui/core";
    import Select from "@material-ui/core/Select";
    import "./styles.css";
    import {
      ValidatorForm,
      TextValidator,
      SelectValidator
    } from "react-material-ui-form-validator";
    
    function App() {
      return (
        <div className="App">
          <ValidatorForm onSubmit={() => {}} className="" autoComplete="off">
            <FormControl>
              <InputLabel shrink={true} htmlFor="age-simple">
                Age
              </InputLabel>
    
              <SelectValidator
                required
                value=""
                name="name"
                displayEmpty
                validators={["required"]}
                errorMessages={["this field is required", "email is not valid"]}
                inputProps={{
                  name: "age",
                  id: "age-simple"
                }}
                input={<Input id="age-simple" />}
                className=""
              >
                <MenuItem value="">
                  <em>None</em>
                </MenuItem>
                <MenuItem value={10}>Ten</MenuItem>
                <MenuItem value={20}>Twenty</MenuItem>
                <MenuItem value={30}>Thirty</MenuItem>
              </SelectValidator>
            </FormControl>
            <Button type="submit"> submit</Button>
          </ValidatorForm>
        </div>
      );
    }
    
    const rootElement = document.getElementById("root");
    ReactDOM.render(<App />, rootElement);

**Comment by NewOldMax** [comment]
Hi,
`SelectValidator` uses `TextField` with select mode, so you should use `SelectProps`:
````javascript
    <SelectValidator
            value=""
            name="name"
            validators={["required"]}
            errorMessages={["this field is required"]}
            SelectProps={{
                displayEmpty: true,
            }}
    >
````
