### ISSUE TITLE
'isEmpty' - TextValidator

### ISSUE THREAD

**Issue by FintanK** [NewOldMax/react-material-ui-form-validator#9]
When using the isEmpty validator it highlights the field only when there is text. It should only do this when the field has been modified and is empty.

![image](https://cloud.githubusercontent.com/assets/2451523/26292076/89685162-3ef6-11e7-9785-c078363e8aef.png)

**Comment by NewOldMax** [comment]
`isEmpty` rule means that input should be empty, it's a opposite of `required` rule.
You can add your own `isNotEmpty` rule by `addValidationRule` function.
