### ISSUE TITLE
why label showing inside select box ?

### ISSUE THREAD

**Issue by naveennsit** [NewOldMax/react-material-ui-form-validator#90]
Hi
why my select box label display inside the `select` box  .Take a example i am not using react -material-validator .it show like this
https://codesandbox.io/s/5vr4xp8854

when i tried to  validate my select box using react-material-ui-form-validator plugin my label come inside the select bx why 
here is my code
https://codesandbox.io/s/38x8q8zpm5

<img width="319" alt="screen shot 2018-09-13 at 6 49 34 am" src="https://user-images.githubusercontent.com/1848972/45461541-3c673280-b721-11e8-89bf-31ac010069da.png">

Secondly when I submit my label is not display in red color why ?

**Comment by NewOldMax** [comment]
Hi
you didn't pass `shrink` param properly. It should be in `InputLabelProps`
[here ](https://codesandbox.io/s/vn3qo8j293)is your fixed example (also it turns to red when you submit it)
