### ISSUE TITLE
Wrong error message and validation for `matchRegexp` validator

### ISSUE THREAD

**Issue by shackra** [NewOldMax/react-material-ui-form-validator#92]
minimal reproducible example https://codesandbox.io/s/1v9n3p6wzl

issue: when you write a number that do not match the regular expression the wrong alert message is displayed. Also, the field is not immediately validated after editing (this is true for controlled components too)

At first I though this issue was related to conditionally setting the validators and error messages but after playing with the other two fields I came to the conclusion it was widespread.

**Comment by NewOldMax** [comment]
Hi
you have several issues in your code example:
1) wrong regexp: should be `matchRegexp:^\\d{3,}$`, but you have `matchRegexp:^d{3}$`
2) this library is designed to work with controlled inputs only, so you must provide `value` prop
3) you must remove native `required` prop if you have `required` validator already

here is a [fixed sandbox](https://codesandbox.io/s/4x8vw7mw79)

**Comment by shackra** [comment]
Silly me, thank you very much!
