### ISSUE TITLE
isFormValid doesn't work as expected

### ISSUE THREAD

**Issue by metal03326** [NewOldMax/react-material-ui-form-validator#94]
Hello.

I'm trying to disable submit button to my form when there is an error, but the `isFormValid()` runs the check apparently too early, as it validates based on the value before the last change. Consider this simple example: https://codesandbox.io/s/ww0lon92k - email is not required, but once one character is typed it becomes invalid. So far so good. Problem is `render` runs `this.form.isFormValid()` to figure out disabled state of submit button and that `isFormValid()` returns `true` even though it is not and the error help text is shown. If I delete this character, then error help text disappears (as it should), but the submit button gets disabled, because `isFormValid()` now returns `false` (should be `true`).

Is this a bug or a feature? If it's a feature, how to get around this problem? Seems confusing.

**Comment by NewOldMax** [comment]
Hi, it's better to handle form state in your component and use it
here is a [fixed example](https://codesandbox.io/s/m9zmwjq6qp)
