### ISSUE TITLE
Validation API docs

### ISSUE THREAD

**Issue by abhishekover9000** [NewOldMax/react-material-ui-form-validator#95]
Could not find any documentation of available validations that come out of the packet. might be useful to add a list where we could collaboratively build a set of validations

**Comment by abhishekover9000** [comment]
just made a PR on this

**Comment by NewOldMax** [comment]
All API is described in [core package](https://github.com/NewOldMax/react-form-validator-core), this one is only implementation for material-ui

**Comment by abhishekover9000** [comment]
all good made a PR to add visibility for other users, up to you if you want to accept it or not
