### ISSUE TITLE
addValidationRule REST query

### ISSUE THREAD

**Issue by jknyght9** [NewOldMax/react-material-ui-form-validator#98]
I am attempting to make a REST query within a addValidationRule and for some reason I continue to get a false result. The goal is to check the backend to see if the supplied email is unique. Here is my code:

```
    ValidatorForm.addValidationRule('isEmailUnique', (value) => {
      const emailRegex = /^((([!#$%&'*+\-/=?^_`{|}~\w])|([!#$%&'*+\-/=?^_`{|}~\w][!#$%&'*+\-/=?^_`{|}~\.\w]{0,}[!#$%&'*+\-/=?^_`{|}~\w]))[@]\w+([-.]\w+)*\.\w+([-.]\w+)*)$/
      if (value.match(emailRegex)) {
        this.props.instructorStore.isEmailUnique(value)
          .then(res => {
            if (res.isUnique)
              return false
            else
              return true
          })
          .catch(err => console.log(err))
      }
    })
```
The isEmailUnique function returns either a true or false result. Is there something I am missing?

**Comment by NewOldMax** [comment]
Hi
sorry, currently this library is not supported promises for validations :(
if you have some ideas how to implement this, please make a PR

**Comment by jknyght9** [comment]
To include async/await?

**Comment by ajayarjun-bka** [comment]
@jknyght9 Were you able implement that feature.

**Comment by NewOldMax** [comment]
Now you can use promises as well
Check the `2.0.6` version

**Comment by ajayarjun-bka** [comment]
When using promises, form **submit** action is getting triggered even when  a field validation error is present. Previously when i was not using promises the **submit** action will not get triggered when there is a field validation error

**Comment by jknyght9** [comment]
Awesome! Thank you very much.

- Jacob

**Comment by NewOldMax** [comment]
@ajayarjun-bka can you create an example at [codesandbox](https://codesandbox.io/s/new) with your issue?

**Comment by NewOldMax** [comment]
@ajayarjun-bka please test new `2.0.7` version

**Comment by hirokihokari** [comment]
@NewOldMax Sorry, is this supposed to work or am I not getting something fundamental?
https://codesandbox.io/s/jv0n5w3kqy?fontsize=14

**Comment by NewOldMax** [comment]
@hirokihokari 
1) you should use `2.0.7` version
2) you should return value in validation rule
```jsx
return response.then(() => {
   return true;
});
```

**Comment by hirokihokari** [comment]
@NewOldMax Silly ME! Works perfectly with the suggestion.

**Comment by fqlx** [comment]
Is it possible to use async/await?
